### ISSUE TITLE
Wish - changelog/what's new on homepage

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#107]
Is it possible to add a changelog or a 'most recent recipes' page to the site? Someone on AMIA-L recently asked for something somewhat similar, though I think he wanted updates posted on the listserv instead. It could be useful for visitors who may not notice that a new recipe has been added, and it could also be a useful promotional tool as we could link to the new scripts on various public forums.

I'm not sure if linking to the commit history would be the best way to go about it as it could confuse people not familar with github.

**Comment by retokromer** [comment]
Linking to the commit history could have... the contrary effect on people not familiar with software development. I guess.

Posts on AMIA-L would be more effective. I guess.

**Comment by kieranjol** [comment]
I agree that listserv posts would be more effective, but I think ffmprovisr is also used by people who are not on AMIA-L, so maybe a changelog could be useful for these users.

**Comment by ablwr** [comment]
I'm interested in this. Wondering how something like this could be scripted out... similar to (what I need to update) the Git HatRack that pulls out all people who are code contributors and general contributors and pops that into the README. Buuuuuut this might have to be a a manually-accomplished thing. "Curated!"

**Comment by retokromer** [comment]
A text that fits for both AMIA-L and other publications (including here on ffmprovisr) could be the best.

**Comment by ablwr** [comment]
A test?

**Comment by retokromer** [comment]
Just corrected typo ;-)

**Comment by ablwr** [comment]
I didn't know that ffmprovisr had gotten any hype on AMIA-L!!! 😇

**Comment by kfrn** [comment]
@kieranjol has done a little promotion on the AMIA-L :)

**Comment by kieranjol** [comment]
http://lsv.uky.edu/scripts/wa.exe?A2=ind1610&L=amia-l&D=0&P=11791 
I think I got frustrated with that thread and stopped replying. Anyhow as you know I don't have any web skills but I'd gladly help retrospectively create a changelog and help update when new scripts are written.

Not sure if a retrospective changelog needs to go all the way back to the beginning, but I definitely think that it should cover the last few recipes..

**Comment by ablwr** [comment]
I don't know how to do this outside of someone coming in and reviewing the recent updates and being like "This is worth hyping on the internet!" So it might have to just be that? Also sometimes we have bursts of activity and other times it's pretty quiet.

**Comment by ablwr** [comment]
I might shout out the recent activity on AMIA-L in order to try to drum up some new recipe requests for the issue tracker as there's not too much to tackle right now that isn't already assigned out!

**Comment by ablwr** [comment]
I posted about it on A M I A 
http://lsv.uky.edu/scripts/wa.exe?A2=ind1611&L=amia-l&F=&S=&P=10304

**Comment by kieranjol** [comment]
+111111111111

It's great that CRALS/SourceCaster got a shout too. Thanks Ashley!

**Comment by ablwr** [comment]
I added them to the readme too!

**Comment by kfrn** [comment]
This is great @ablwr! Thanks!

**Comment by ablwr** [comment]
This is still a manual process but I was thinking of shouting out to AMIA-L soon about @kfrn's Windows script, the filters from @privatezero's talk, the QCTools scripts I just added, and #118 if I get around to it. 👍 ?

**Comment by retokromer** [comment]
WTF is AMIA-L?

**Comment by todrobbins** [comment]
@retokromer, I think it's the AMIA mailing list.

**Comment by retokromer** [comment]
@todrobbins I know ;-)

**Comment by todrobbins** [comment]
You got me!

**Comment by retokromer** [comment]
We could integrate this with formal releases. I guess that would be a good way to do it. Thoughts?

**Comment by ablwr** [comment]
My thoughts are that @retokromer is a genius 😇

**Comment by retokromer** [comment]
I published the [first release](https://github.com/amiaopensource/ffmprovisr/releases/tag/v2017-02-18). When we publish the next one, we could include the relevant commits in the description, and use this for advertising as well.

I used as versioning convention the actual date of the release `vYYYY-MM-DD`, because I guess this is the easiest and most intuitive.
