### ISSUE TITLE
mp3 constant quality

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#110]
In the WAV to .mp3 script ffmprovisr gives instructions for a constant bit rate which will result in access files that are significantly larger than if a constant quality setting was used.
http://amiaopensource.github.io/ffmprovisr/#wav_to_mp3  

FFMpeg's documentation suggests that anything set between -qscale:a 0 and -qscale:a 3 should in most cases be indistinguishable from files encoded with the max constant bitrate in terms of sound quality:
https://trac.ffmpeg.org/wiki/Encode/MP3.

Is this worth revising, or making a note about constant quality vs bit rate?

**Comment by ablwr** [comment]
I think it's worth revising and noting!!!

**Comment by retokromer** [comment]
I suggest to add also a note for http://amiaopensource.github.io/ffmprovisr/#transcode_h264 about `-qp` vs `-crf`. In my opinion, in an archival context, `-qp` should be preferred.

**Comment by privatezero** [comment]
Made some changes for constant quality on my branch here: https://github.com/amiaopensource/ffmprovisr/commit/5ecc763f6dd9f9cc447d3933c5c75b56c41a46e4#diff-eacf331f0ffc35d4b482f1d15a887d3b. What do peeps think of the wording?

**Comment by retokromer** [comment]
LGTM

**Comment by ablwr** [comment]
Resolved, yes?

**Comment by retokromer** [comment]
Solved in https://github.com/amiaopensource/ffmprovisr/pull/111/commits/5ecc763f6dd9f9cc447d3933c5c75b56c41a46e4
