### ISSUE TITLE
issues with thumbnail generation

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#112]
There seem to be some overlaping/broken commands in this section.

https://amiaopensource.github.io/ffmprovisr/#thumbnails
This command is called "generate thumbnails" in the plural, but actually seems closer to the script for generating only one. The explanation within this command also refers only to making a thumbnail "at a specific time" so there is discrepancy between the title and explanation.

Additionally, in its current form with an extra input tied to a variable, the script is broken.  Is this a typo, or was it trying to do something else that accidentally didn't make it into the final script?  (Since the annotations don't mention anything else I suspect the first explanation).

Since there already are commands for creating both single and multiple thumbnails, is this  command redundant?

**Comment by retokromer** [comment]
Thank you, @privatezero, for reporting this!

**Comment by retokromer** [comment]
Just in case: I did __not__ solve the issue. Volunteers very welcome!

**Comment by ablwr** [comment]
Was this corrected? The above link doesn't lead anywhere.

**Comment by privatezero** [comment]
I didn't delete it, but it looks like someone did!

**Comment by ablwr** [comment]
Oh, it's there in the code and I now see that @retokromer commented it out. I think we can scrap this recipe since there are two others for generating thumbnails, for single-thumbnail and multi-thumbnail.

**Comment by privatezero** [comment]
👍👍

**Comment by retokromer** [comment]
Yes, as said above, I commented out the section because, as @privatezero reported, the result was wired and wrong. I did not have had the time to delve into this so far, but I will probably do so during next weekend.

**Comment by retokromer** [comment]
Solved by https://github.com/amiaopensource/ffmprovisr/pull/123/commits/ea9cb9c83b8910e3506fa7accdd8c834e13587f2

**Comment by ablwr** [comment]
Yeah I don't know how to read, I guess. Thanks @retokromer!
