### ISSUE TITLE
Add CRALS/sourcecaster

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#113]
We link to CRALS and Sourcecaster in the README but I think we should link to it on the site itself, underneath the link to the CLI learning resource. I can do this but not at this time, so filing an Issue for the middle period (or if someone else wants to do it).

**Comment by kfrn** [comment]
[You rang?](https://github.com/amiaopensource/ffmprovisr/pull/114) :)

**Comment by ablwr** [comment]
Are you the greatest orrrrrrr the greatest???

**Comment by kfrn** [comment]
I reckon this is good to close :)
