### ISSUE TITLE
Join Files Together - Clarifications needed

### ISSUE THREAD

**Issue by metacynicv2** [amiaopensource/ffmprovisr#115]
Heya,

Has anyone successfully concat files using this method? https://amiaopensource.github.io/ffmprovisr/#join_files

The language is a little unclear and I have not had success. 

Attached is how I interpreted how to create the join list, but I keep getting the also attached error. 

If there are any other possibly more simple methods for successfully joining DV files I'd be in love. 

![screen shot 2016-12-02 at 5 49 16 pm](https://cloud.githubusercontent.com/assets/9436241/20855835/b9695a7a-b8b7-11e6-9da4-048be249786a.png)

[BAVC1004511_2385M.txt](https://github.com/amiaopensource/ffmprovisr/files/628627/BAVC1004511_2385M.txt)

**Comment by kfrn** [comment]
Hmm, it looks alright. I think I wrote or amended that command, so I know that it worked for me. Could using the curved quote marks (**‘’**) rather than straight apostrophes (**'**) be throwing things off?

**Comment by metacynicv2** [comment]
Hi @kfrn - you are perfect. Changing the apostrophes from curvy to straight worked. Thank you!

**Comment by kfrn** [comment]
Glad it worked! I'll add a note into the recipe too :)

**Comment by retokromer** [comment]
Indeed, never use typographic style for commands! Some text editors do this by default, but it should be possible to disable this «feature».
