### ISSUE TITLE
write demo of scene change splitting

### ISSUE THREAD

**Issue by dericed** [amiaopensource/ffmprovisr#12]
Here's a start. I think it would need to be in two passes, one to get the scene change times and one to split, so first pass with signalstats and 2nd with the segment muxer.

This command outputs a csv of the time of scene change and the YDIF value. I'm using 10 below as a scene change threshold, adjust as needed.

```
ffprobe -f lavfi movie=HEY.mkv,signalstats -show_entries frame=pkt_pts_time:frame_tags=lavfi.signalstats.YDIF -of compact=p=0:nk=1:s=',' | awk -F, '$2 > 10'
```

The csv could then be processed to make it an input to the segment_times option of the segment muxer, see: http://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment

**Comment by jronallo** [comment]
Yes, this seems like a good start. Using awk is a nice shortcut to show how this could work but I think a fuller solution does call for a script that does some analysis of the YDIF values throughout and sets a cut-off value that fits the individual video. For some cases you'll also want to do some grouping as some scene changes aren't just quick cuts.

@dericed I also wonder if there's any other analysis that ffprobe might be able to do on the frames? So for my purposes a scene cut will often be a frame or second of black, so it would be nice to be able to filter these out. But again that could be a post-processing job after ffprobe does the general analysis of change.

**Comment by kieranjol** [comment]
I remember trying the command mentioned by @richardpl in this thread, probably combined with a second pass of `ffmpeg -i <inputvideo> -vf select='gt(scene\,0.7)' -vsync 0 -an keyframes%03d.jpg` and it did a really god job of grabbing scene changes from a feature. 
https://ffmpeg.org/pipermail/ffmpeg-user/2016-April/031962.html

**Comment by retokromer** [comment]
This in now open since approximately one year... cc @dericed @ablwr @jronallo @kieranjol

**Comment by richardpl** [comment]
You could use metadata filter instead of awk to pass pts when signalstats metadata numbers change.

**Comment by pjotrek-b** [comment]
Also interested.
Any updates / more practical experiences on this?

**Comment by retokromer** [comment]
Is someone working on this?

**Comment by ablwr** [comment]
🤔

**Comment by ablwr** [comment]
happy 2-year birthday to this issue, as a gift I am closing it
