### ISSUE TITLE
Batch processing for Windows?

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/ffmprovisr#128]
Hi all, I have a batch script for Windows (PowerShell) that I could add as a separate command.  
Maybe we have some Windows users that would like to automate tasks. What do you all think?

**Comment by ablwr** [comment]
Yes yes yes, Windows users need support too!

**Comment by kfrn** [comment]
Great. I'm on it!

**Comment by kfrn** [comment]
Pull request [here](https://github.com/amiaopensource/ffmprovisr/pull/129)

**Comment by retokromer** [comment]
Merged, thank you!
