### ISSUE TITLE
ffmpeg installation instructions (or link)

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#134]
think it would be beneficial to add ffmpeg installation instructions (or possibly, a link to @retokromer 's excellent FFmpeg cookbook, https://avpres.net/FFmpeg/).

I really like the "Testing Your Installation" section; I find it super helpful.

**Comment by kfrn** [comment]
Perhaps a link to Reto's installation info (https://avpres.net/FFmpeg/#ch1) in the sidebar?

**Comment by ablwr** [comment]
+1 for this. I can add it in a few hours if someone doesn't beat me to it ( @kfrn is very good at this)

**Comment by kfrn** [comment]
That sounds like a challenge @ablwr !

**Comment by kfrn** [comment]
Cough ... #135

**Comment by ablwr** [comment]
hahahahha best
