### ISSUE TITLE
"install with homebrew" instructions

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#140]
Please see the conversation in this thread: https://github.com/amiaopensource/ffmprovisr/pull/139

**Comment by retokromer** [comment]
I guess this has been resolved in https://github.com/amiaopensource/ffmprovisr/commit/2c0e555dc1294be05785dd204630165c30be92e6.

**Comment by ablwr** [comment]
We can re-open if we decide to re-visit.
