### ISSUE TITLE
Wish: Better documentation

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#16]
Boost up documentation on contribution guides and ways people can contribute / make it as easy as possible for contributions to happen.

**Comment by ablwr** [comment]
I updated this a lil bit but it would be good to have feedback from people coming across it!

**Comment by retokromer** [comment]
My nieces and nephews have tried it. Usually they found the description obscure, but then they rapidly have performed many recipes alone.

**Comment by ablwr** [comment]
!!!!!!!!!!!!

**Comment by ablwr** [comment]
This issue refers to the readme.md and how to make contributing scripts easier. I think I made it as user-friendly as possible and documentation is a continual process so I'll go ahead and close this ticket.
