### ISSUE TITLE
How to deal with non-FFmpeg commands in ffmprovisr?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#168]
As @pjotrek-b suggested in https://github.com/amiaopensource/ffmprovisr/issues/76

**Comment by pjotrek-b** [comment]
As @kieranjol already pointed out in his posting on #76:
[Sourcecaster](https://datapraxis.github.io/sourcecaster/) and/or [Script Ahoy](http://dd388.github.io/crals/) might be good places to contribute them to.

**Comment by ablwr** [comment]
As commented in previous thread, I'm still in favor of not restricting to only ffmpeg commands, as long as still in the scope of avpres.

**Comment by retokromer** [comment]
We have now two Bash scripts:
- `check_audio_framemd5.sh`
- `check_video_framemd5.sh`

beside the main page `index.html`.

**Comment by kfrn** [comment]
Script subfolder?

**Comment by ablwr** [comment]
For these, yeah, maybe they should go in a script subfolder instead of at the top. +1 @kfrn

**Comment by retokromer** [comment]
I was also thinking about a folder. I was just waiting for this, hoping that the suggested combined recipe to generate and script to verify the MD5 of both image and sound in one go will be made… by someone else than me.

**Comment by retokromer** [comment]
Should I name the folder `bash`, `script`, `bassir`,…?

**Comment by retokromer** [comment]
Resolved by https://github.com/amiaopensource/ffmprovisr/pull/175.

**Comment by pjotrek-b** [comment]
About "**script to verify MD5 of both image and sound**":
Could take a look at it. 2 things to clarify though:

  1. Current scripts framemd5 video/audio separately. For a combined framemd5 check, it might make sense to add the 3rd option that produces 1 framemd5 for video+audio combined?
  2. I'd need someone to test on MacOS (I guess?)

**Comment by retokromer** [comment]
I personally was thinking about **_two_** distinct MD5 files which can be:
- generated either by the two individual recipes or the to-do combined recipe
- verified either by the two individual scripts or the to-do combined script

**Comment by pjotrek-b** [comment]
Affirmative.
