### ISSUE TITLE
Suggestion: Splitting "change formats" into "change codec/container" and "change formats"?

### ISSUE THREAD

**Issue by pjotrek-b** [amiaopensource/ffmprovisr#169]
I caught myself wishing to separate the existing entries in "Change formats" into 2 categories:
  1. Change codec/container
  2. Change formats

I think that might make it easier and clearer for non-experienced users to find what they're looking for?
Just a suggestion.

If you agree, then I'd provide the patch.

**Comment by retokromer** [comment]
I personally prefer to distinguish in a more pedantic way between

- change container
- change codec
- change format

But if it’s just me, then of course I’ll agree.

**Comment by pjotrek-b** [comment]
Yes, absolutely agreed!
I loooove sorting things properly :grin:

**Comment by pjotrek-b** [comment]
Hm... Ran into the first issue:
"_WAV to MP3_" is actually of both: "change container + codec"

But I'd suggest if transcoding happens, to put it under "change codec".
I'd also suggest to put only "-c copy" entries in "change container".

**Comment by retokromer** [comment]
Agreed.

**Comment by ablwr** [comment]
Also agree. Thanks @pjotrek-b, 👑 👑 👑

**Comment by retokromer** [comment]
resolved in https://github.com/amiaopensource/ffmprovisr/pull/172 by @pjotrek-b (thank you :-)
