### ISSUE TITLE
add script for audio normalization

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#178]
ebur128?

**Comment by privatezero** [comment]
Are you interested in a formula for the ebur128 visualizations or the actual normalization using loudnorm?

**Comment by bturkus** [comment]
I was thinking loudnorm, but maybe it'd be good to add both?

**Comment by privatezero** [comment]
yeh, that makes sense! I'll try to put something together this weekend!

**Comment by bturkus** [comment]
thanks @privatezero you da best!
