### ISSUE TITLE
Which is the correct licence?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#190]
- the [readme.md](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/readme.md#license) states CC BY 4.0
- the [index.html](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/index.html#L33) states CC BY-SA 4.0

**Comment by ablwr** [comment]
Good catch! I'm inclined to stick with the README and use CC BY 4.0. What do others think?

**Comment by ablwr** [comment]
I believe I added the CC BY-SA 4.0 to the index because CC was not stated there, only in the README. I grabbed it from the Cable Bible but erroneously thought they were using the same license.

**Comment by ablwr** [comment]
I'm also fine with CC-0.

**Comment by retokromer** [comment]
My preference is for CC BY, followed by CC 0.

**Comment by ablwr** [comment]
I also wouldn't want to change it up to CC-0 all the sudden when people have contributed with the expectation of CC BY.

**Comment by privatezero** [comment]
I'm down with CC BY, also totally ok with a CC-0 change!
