### ISSUE TITLE
add audio mapping to video trimming recipes?

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#196]
There are a few trimming recipes in ffmprovisr, exceprt from beginning, from end, from middle etc.. They use `-c copy`, but I think that they should also use `-map 0` so that all streams are copied? I saw someone use the recipe to trim a video that had two audio tracks, but only the first track was copied to the output due to ffmpeg defaults. I'd like to know what ye all think before proceeding with pull requests.

Best,

Kieran.

**Comment by retokromer** [comment]
Indeed! Please send a PR.

**Comment by kfrn** [comment]
Good call! Great idea to update that.
