### ISSUE TITLE
Wish: Lump issues into categories

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#2]
Sort the code blocks into categories with subheadings for better organization of information. This ticket entails thought towards how to best categorize these scripts and also implementation of that categorization. Ideas for categories are something like... access copy creation, format transformation, exporting, image extraction, snippet extraction, digital preservation methods.

**Comment by retokromer** [comment]
I agree, we need to group the recipes into categories.

**Comment by ablwr** [comment]
With consideration to the 20-ish scripts up there right now, I'm thinking of splitting into these categories of use/reference for now. 
- Change format
  (mp3 to wav, to prores, h264 to/from anything)
- Make derivative variations
  (thumbnails, excerpts, split audio/video)
- Preservation
  (make checksum, batch processing, pull specs)

I suppose a change of format could mean a derivative, but do you think it makes sense, that I mean either doing a transformation of the foundations or making smaller versions?

cc @retokromer

**Comment by retokromer** [comment]
On my side, I made a distinction between transcoding and filtering, but that supposes that the user clearly know what this means, i.e. what is the difference. I guess _ffmprovisr_ has another, more intuitive approach.

Batch processing has to do with automatisation of repeated tasks, not with preservation, and it can be applied to more or less to everything. Perhaps a category «advanced» transformations? This could include other «tricky» stuff. I would include here also e.g. the watermark recipe.

cc @ablwr @kieranjol

**Comment by retokromer** [comment]
Perhaps https://github.com/amiaopensource/ffmprovisr/issues/17 can be merged with this «issue»?

**Comment by ablwr** [comment]
OK, I am going to close #17 and we can continue here. I'm still not sure how this 3D structure might play out and what kind of code would be needed to make this flow happen. It sounds like it could be useful though.
