### ISSUE TITLE
batch processing - mac - add recursive find?

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#207]
I think it might be worth adding a `find` example to the batch process recipe for mac? Maybe using the same example as the `for` loop, maybe:
`find -name "*.MXF" -exec ffmpeg -i {} -c copy -map 0 {}.mov \;`
or something?

**Comment by kfrn** [comment]
I like it! Didn't know that method, so thanks. 
What does the `\` do here? I've only used backslashes to continue a command over multiple lines.

(For reference: existing command [here](https://amiaopensource.github.io/ffmprovisr/#batch_processing_bash))

**Comment by retokromer** [comment]
We could also change the extension `.MXF` to `.mxf` in the recipe, because small caps are much more frequent.

**Comment by dericed** [comment]
-iname is case insensitive -name
The {} should be double quoted to avoid spaces breaking things.

**Comment by retokromer** [comment]
>-iname is case insensitive -name

Indeed, but didactically – if we wish to include also beginners – I think it’s better to use the most common writing.

**Comment by ablwr** [comment]
Good to use one and mention the other in the explanation!

**Comment by kieranjol** [comment]
Hi! Thanks all, and yes @dericed , `-iname` would be more useful and I generally use that instead of `-name`. 
@kfrn the slash is just an escaping character for the `;` which ends the statement.

**Comment by retokromer** [comment]
> Good to use one and mention the other in the explanation!

I don’t think that using `.mxf` and mentioning in the explanation `.MXF` would be of interest. And, if really so, should we also double all the `.mov` and `.MOV`, etc.?

**Comment by kieranjol** [comment]
I'm all for using lower case across the board for file extensions..

**Comment by kfrn** [comment]
I'm happy to go through and normalise filename extensions to lower-case.
