### ISSUE TITLE
Question: Transcode to H.265/HEVC

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#208]
By default x265 is compiled for 8-bit. Should we consider also the possibility to compile it for 16-bit?
```
brew reinstall x265 --with-16-bit
```

**Comment by kieranjol** [comment]
Sure, i think that's great info to know. I didn't know that x265 had that feature. I know that x264 has a 10-bit mode, but doesn't that 10-bit version only allow you to encode 10-bit, so 8-bit pixel formats are no longer available? Is the 16-bit mode the same, in that it would prevent 8-bit encoding?

**Comment by retokromer** [comment]
For x264 we have the following information on our website:

### For advanced users

`yuv420p` is an 8-bit pixel format, which is common among distributors. For a bit depth of 10, which is common in video post-production, the pixel format `yuv420p10le` may be used, yet the library libx264 must be compiled in 10-bit mode for this. By the way, in this case the range of the quantiser scale for `-qp` and `-crf` is from 0 to 63.

If ffmpeg is linked to libx264 dynamically rather than statically, then it will adapt automatically to the bit depth supported by the run-time libx264, regardless of the version used at build time. This way it’s possible to work either 8-bit or 10-bit in each ffmpeg command; however you cannot combine 8-bit and 10-bit in the same command, you need two commands.

**Comment by retokromer** [comment]
This may change in the near future (see https://github.com/Homebrew/homebrew-core/pull/19124).

**Comment by retokromer** [comment]
Resolved in https://github.com/Homebrew/homebrew-core/pull/19124.
