### ISSUE TITLE
Wishlist: search functionality

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#211]
Hi,
I was wondering about the possibility of adding a search function to ffmprovisr. Now that there are so many commands on there, I've actually had some difficulty locating specific items. If I could search for, say "yuv420p," or whatever else, I think that would be really helpful.
Thanks,
Ben

**Comment by ablwr** [comment]
Ohhh... hmmm... I think this might be possible, yeah. For AVAA I use this client-side javascript library (which means it can still be hosted simply on Github pages and not require a server). Maybe we can integrate that. Anything bigger would require a bigger hosting platform.

**Comment by retokromer** [comment]
As one HTML page contains all the information, it should not be difficult to program a solution that works both online and offline.

**Comment by ablwr** [comment]
ctrl-f

**Comment by retokromer** [comment]
Hmm… I would prefer something more user friendly.

**Comment by kfrn** [comment]
Recently, I was thinking about the idea of being able to tag different commands. But this would require quite a restructuring of ffmprovisr (as, probably, would search ability).

**Comment by retokromer** [comment]
I agree. The Cable Bible could be restructured as well.

**Comment by ablwr** [comment]
Joking about ctrl-f; it doesn't work.

I support searching and tagging! I agree that tagging would require some restructuring -- do you have something in mind? Search probably wouldn't require a restructuring, but could (if it is overall better for the site). 

Ideas?

Or: Ideas for how we can best brainstorm up a solution together?

**Comment by retokromer** [comment]
> Joking about ctrl-f; it doesn't work.

It cannot work ;-)

> Ideas?

I guess, I would split it into the single recipes. As we give the possibility to install and update locally via Homebrew/Linuxbrew, that should be fine also when the internet connection is bad.

**Comment by ablwr** [comment]
Like replicating the way [AVAA](https://bavc.github.io/avaa/) is structured?

**Comment by retokromer** [comment]
I should check that more carefully, but I have the impression that this is completely hard-coded. I would suggest a solution that creates a query’s answer on the fly. (Because it’s easier to maintain.)

**Comment by ablwr** [comment]
AVAA uses lunr.js, a lightweight client-side search service built in JavaScript!

**Comment by retokromer** [comment]
Thank you for the information! Yes, something like that. (My websites use a Perl script and a MariaDB database to generate most of the pages on the fly since more than 20 years.)

**Comment by ablwr** [comment]
I built the site so I should know! 😆 🚀 🎸 Just depends on if we want to go that route instead of the one-pager-with-modals we have now. Modals aren't great, but I do appreciate the simplicity. I'm sure there's an even less complex solution for searching all within the one page in a user-friendly way. 

One major issue about restructuring that I want us to consider early on is that we don't want to cause any URL-breaking, and splitting things up would potentially cause that. We'd have to think carefully about a redirect solution (I also had to do this with AVAA, a large reason for the search being the way it is).

**Comment by retokromer** [comment]
> 😆 🚀 🎸

:1st_place_medal: 

> I'm sure there's an even less complex solution for searching all within the one page in a user-friendly way.

Indeed! I’m thinking about something like the good old `<ISINDEX>` tag… but newer.

**Comment by kfrn** [comment]
Yeah, there are definite tradeoffs re: functionality v. complexity to be considered.

**Comment by retokromer** [comment]
During my recent teaching, I made the experience that many beginners consider the current [homepage](https://amiaopensource.github.io/ffmprovisr/) a little intimidating. I guess, we would need also some introductory prose, suggesting possible exploration routes.

**Comment by ablwr** [comment]
Please open a new issue to discuss this!

**Comment by retokromer** [comment]
It’s related to this discussion: if we wish to restructure the site for adding search possibilities, or if we don’t.

**Comment by ablwr** [comment]
In that case we should edit the title of this issue to make it more broad and not specific to search

**Comment by ablwr** [comment]
Now that the recipes can be opened on the page instead of in a modal-box, it is possible to have a "open all recipes" button that will allow a user to use ctrl-f to search and find on the page. Would that be helpful for solving this feature request?

**Comment by bturkus** [comment]
yeah that sounds great

**Comment by retokromer** [comment]
>Now that the recipes can be opened on the page instead of in a modal-box, it is possible to have a "open all recipes" button that will allow a user to use ctrl-f to search and find on the page.

Are you working on this, @ablwr?

>Would that be helpful for solving this feature request?

Indeed! I guess as well that this would be a very useful improvement.
