### ISSUE TITLE
Scene Detection using YDIF

### ISSUE THREAD

**Issue by drodz11** [amiaopensource/ffmprovisr#213]
In inquiring about using QC Tools for scene detection in a media analysis project, @dericed offered this ffprobe command that (for me, at least) usefully prints a .csv correlating timestamps and their YDIF values. In my tests so far it's a fairly accurate way of determining cuts, but I need to experiment with the thresholds on the spreadsheet side a bit more. Anyway, I figured this might be useful to those (like me) getting acquainted with the functionalities of ffmpeg and already very grateful for ffmprovisr. Code below:

`ffprobe -f lavfi -i movie=YOUR_MOVIE_HERE.MKV,signalstats -show_entries frame=pkt_pts_time:frame_tags=lavfi.signalstats.YDIF -of csv`

Link to original discussion on QC Tools repo: https://github.com/bavc/qctools/issues/422

**Comment by todrobbins** [comment]
🔥 RAD🔥

**Comment by todrobbins** [comment]
`<threadjack>`
How does scene detection using YDIF compare to [scene fingerprinting/perceptual hashing](https://amiaopensource.github.io/ffmprovisr/#compare_video_fingerprints)? I know @privatezero has [worked on this](https://ndsr.americanarchive.org/2017/04/20/adventures-in-perceptual-hashing/) as well, and I'd love to understand these methods better.
`</threadjack>`

**Comment by drodz11** [comment]
@todrobbins ,

Thanks for sharing info re: perceptual hashing! Based on what I've looked at here it seems that the primary difference between scene detection using YDIF vs. perceptual hashing is that large values or "spikes" in YDIF tend to correspond to cuts, whereas perceptual hashing seems more useful in detecting similar content across files using more arbitrary forms of segmentation (i.e. not looking at the media "as edited" but breaking it up into manageable chunks of frames, as discussed by @privatezero ). If you look at the screen grab from QC Tools below, you'll see on the bottom graph a green line representing YDIF values. The "spikes" (most of the time) correlate with cuts in the video. Using the ffprobe command above, I am able to export this YDIF data as a .csv and can then view/manipulate in Excel. Adding a filter to the YDIF column of say >20-25 allows me to see these spikes and their corresponding timestamps. It is not 100% accurate (still experimenting with different thresholds and kinds of video files), but the final result is similar to an EDL you might generate in software like Da Vinci Resolve.

The particular project I have been hired to work on is a social science [media content analysis](http://www.historylearningsite.co.uk/sociology/research-methods-in-sociology/media-content-analysis/) project wherein human coders are watching narrative feature films and recording information in an extensive codebook. I've been brought on to research automated processes for supporting this work, and one area I am interested in is scene detection. I am hoping to find a way to "pre-divide" a film into scenes for the human coders so they do not have to go through the tedious task of determining where scenes start and end while also looking at content.

Would definitely be interested in learning more about how perceptual hashing might be used in scene/cut detection though. Perhaps I am missing something here as this is all pretty new to me as an archivist.
![ydiff_spikes](https://user-images.githubusercontent.com/25777161/28788911-d629afce-75f0-11e7-8417-40773620f3bc.jpg)

**Comment by kieranjol** [comment]
Hi @drodz11  - I've been experimenting with concatenating files and inserting chapters for the source in/out points by using the Matroska container.  I was looking at the spreadsheet that is generated by this command and I think that I could easily knock up a script that would:
* Create CSV/JSON report of YDIFS
* Remux file to Matroska container
* Allow user to set YDIF threshold on the command line
* the time values in the ffprobe report are converted to timestamps so that:
* mkvpropedit can insert chapter markers at scene changes.

Lemme know if you're interested in this and you can maybe shoot me an email to discuss more? kieran.o.leary AT gmailDOTcom

Seeing as this ffmprovisr recipe is currently a bit cryptic in terms of how to use the data, perhaps we could link to a script like this that could be an example of how to put it into action.

**Comment by retokromer** [comment]
>Seeing as this ffmprovisr recipe is currently a bit cryptic in terms of how to use the data, perhaps we could link to a script like this that could be an example of how to put it into action.

👍
