### ISSUE TITLE
header tags

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#228]
The header tags are set up according to size of the font... but should really be set according to the significant of the header! This should be reviewed and changed appropriately.

**Comment by retokromer** [comment]
FYI: If the changes of this and the previous two issues could be resolved during the next 2–2.5 weeks, then I will made a new release in time for the FIAF workshop in Chennai, India.

**Comment by retokromer** [comment]
@ablwr Are you working on this?

**Comment by ablwr** [comment]
Yeah. Got distracted but I'll be back at it.

**Comment by retokromer** [comment]
Thank you! Then I wait before making a new release.

**Comment by kfrn** [comment]
Thanks for completing this @ablwr :)
