### ISSUE TITLE
Filtergraph explanation

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/ffmprovisr#233]
Hi all,  
We now have quite a few commands with relatively complex filtergraphs. I was wondering if it would be worth adding a popup on 'Understanding filtergraphs' at the bottom of ffmprovisr, perhaps under a new heading like 'FFmpeg concepts'.    
I started to write something of this type, incorporating the info included in commands like [IVTC](https://amiaopensource.github.io/ffmprovisr/#inverse-telecine), and some of the content of the [ffmpeg wiki page on filtering](https://trac.ffmpeg.org/wiki/FilteringGuide#FiltergraphChainFilterrelationship).  
The idea is that we could link to this 'info-command' in other commands where appropriate, and maybe even streamline some existing commands.  
What do you all think though? Does it add value, or are things fine as they are?

**Comment by privatezero** [comment]
I think that is a great idea!

**Comment by retokromer** [comment]
Excellent idea!
(FYI: I will make in the next 48 hours or so a new release to use at the FIAF workshop in Chennai.)

**Comment by kieranjol** [comment]
Great idea!

**Comment by ablwr** [comment]
Yes! I think this should maybe go at the top instead of the bottom.

**Comment by kfrn** [comment]
Okay, great! I'll flesh out my draft and get a PR out in the next few days.
@retokromer, I'll not have the chance to do it before you head to Chennai, so go ahead and make that release.

**Comment by retokromer** [comment]
Thank you very much, @kfrn! I made a release with the new structure and design. This way the participants get used to it and have not to change… in the middle of the week. That was an important step forward, in my opinion. I will keep updated the gang about the reactions.

**Comment by kfrn** [comment]
Indeed I thought it would be nice to have the increased navigability for your workshop. Yes, please do let us know what people think.

I shall work on filtergraph etc next week :)
