### ISSUE TITLE
r e - d e s i g n ❓

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#235]
Thinking about the open and recently closed issues of header tags #228, filtergraph explanation #233, search functionality #211, and doing a lot of personal-site refactoring to reduce code bloat and increase responsiveness/accessibility, I am thinking...

# Is it time for a re-design?  

I'm very happy to take on this task, but I need some requirements (constraints) from the community to think about the best ways to make ffmprovsr better visually. I think I heard @retokromer mention that students found it visually intimidating (because of the black? because of all the options at once?).

Fellow maintainers, contributors, interested parties, what do you think?

**Comment by kieranjol** [comment]
I think a re-design would be very helpful - I keep hearing from users that it is difficult to find what you want on the page - though they are then full of praise for what ffmprovisr teaches them..

I kinda like the black btw..

And perhaps some refactoring is needed so that things like 'ffmpeg concepts' could be incorporated without adding a flood of more items. I love the idea of the 'concepts', there's room for a lot of tips and tricks that might be worthy of a dedicated ffmpeg wiki page.

**Comment by retokromer** [comment]
>because of the black?

No.
>because of all the options at once?

Yes. And without a clear hierarchy and/or workflow. They need some time to find where to start – today, people are impatient… ;-)

**Comment by ablwr** [comment]
I like the black background too because that is what command line interfaces mostly default to. :)

**Comment by ablwr** [comment]
Not thrilled about our use of modals either -- I think it'd be better to have the text grow/expand out of the button but stay on the page rather than pop up on top of it.

From the technical side, we are also using jQuery and Bootstrap but really don't need either, so we can eliminate a lot of code this way and simplify things. We can probably simplify the formula with which we add new scripts, too.

**Comment by retokromer** [comment]
)Side note 1: currently, ffmprovisr does not work fine on a Braille terminal :-(
(Side note 2: we should say how to pronounce ffmprovisr ;-)

**Comment by kfrn** [comment]
I'm not in love with modals either - a 'click to expand' approach would be good, I think.

**Comment by ablwr** [comment]
I'll be thinking about this. Please ask around or relay what else you've learned from other people coming to this for the first time! I am going to tweet about it cuz that seems to get good results.

**Comment by ablwr** [comment]
I LOVE ASKING PEOPLE WHAT THEY DISLIKE

**Comment by ablwr** [comment]
What do you think of... more space, like this (one is normal screen, other is "mobile size")? I want to prepare for making this look better on smaller devices (by making it all in one column) but also make way for a lot of space on larger screens for a future move to take the modals and move them in-line, so clicking doesn't open up a pseudo-popup but rather shows the recipe right there.

<img width="1679" alt="screen shot 2017-10-08 at 23 24 47" src="https://user-images.githubusercontent.com/3260492/31324394-fd6c71e6-ac7f-11e7-87a9-09c8881e6181.png">
<img width="588" alt="screen shot 2017-10-08 at 23 25 21" src="https://user-images.githubusercontent.com/3260492/31324395-fd79ef56-ac7f-11e7-9ae9-010229a5fb9c.png">

**Comment by ablwr** [comment]
I'm trying to avoid one BIG redesign in favor of small, iterative changes.

**Comment by retokromer** [comment]
During a presentation, increasing the font size, on the screen I got:

<img width="1184" alt="bildschirmfoto 2017-10-12 um 02 35 52" src="https://user-images.githubusercontent.com/3246607/31473664-4e2e6fa8-aef6-11e7-89ce-d0af34e078cc.png">

Can we add a test like: if left column < 3 x right column, then use the one-column layout? I.e. not only absolute, but also relative values.

cc @ablwr @kfrn

**Comment by ablwr** [comment]
Whoops! Sorry @retokromer! I am going to send a PR right now.

**Comment by ablwr** [comment]
That should fix it. And it switches to single-column at 175% zoom, for me. This should be considered in the future because the table of contents buttons lean over the side a little bit at 150%, etc., but it's better to zoom properly and deal with that more-minor aesthetic issue later.

**Comment by retokromer** [comment]
Thank you very much, @ablwr!

**Comment by ablwr** [comment]
I am about to send a big change that moves recipes from Modal mode to Open-inline mode but I am still testing, so hang tight -- this restructures all the recipes!

**Comment by bturkus** [comment]
redesign looks awesome, but I noticed some funky overlaps when browser windows are unusually sized (chrome on mac and windows). like this:

![screen shot 2017-10-13 at 11 09 15 am](https://user-images.githubusercontent.com/8987230/31553062-3ec53f1c-b007-11e7-8ac0-8d848c28b5e5.png)

I'm really loving all the changes! y'all rock!

**Comment by ablwr** [comment]
Haha @bturkus yeah I'm working on fixing an issue related to that right now... it's driving me crazy.

**Comment by ablwr** [comment]
straight up want to put an "under construction" gif up on here cuz I gotta do some real work....

![under_construction](https://user-images.githubusercontent.com/3260492/31553437-7defda20-b008-11e7-9de1-cf010b5d028a.gif)

😅

**Comment by ablwr** [comment]
I used my twitter skills to make the buttons more succinct.

**Comment by ablwr** [comment]
I merged #256 which changes the Table of Contents to a list instead of buttons, which helps with the wonkiness when resizing, as @bturkus pointed out. I was also not seeing the text on any of the ToC buttons in Firefox on my iPhone (but Firefox on desktop was fine). 

That PR (and sorry for convoluting issues together) also changes the link primary color to shades of green, to reflect the green on ffmpeg.org. It ups the font size a little overall, for easier reading, and makes the h2 and h3 tags size themselves in relation to that default size (from 14px to 16px).

There's still a viewport overflow sizing issue also probably caused by one of the longer buttons that makes things not fit onto screens less than ~550px wide.

**Comment by ablwr** [comment]
I'm just digging around wild like a little wild boar on the hunt for truffles 🐷, but please let me know if you don't like something, or something else needs refinement.

**Comment by todrobbins** [comment]
A light and dark mode would be helpful. I like the dark mode, but having a black on white option would be stellar.

**Comment by privatezero** [comment]
Maybe this is just my inner librarian speaking, but perhaps the ToC should be alphabetized? (Apart from pinning informational entries like _About This Resource_  and _Advanced FFmpeg Concepts_?

**Comment by retokromer** [comment]
I guess, if one knows how it’s called, yes; but when one don’t, it’s easier, if similar recipes are grouped.

**Comment by privatezero** [comment]
Wasn't referring to the organization of recipes, rather the organization of the groupings of recipes in the table of contents - while some of these groupings seem conceptually organized, many of them aren't, and the groupings themselves might benefit from additional order?

Alphabetization would at least establish a clear style for any future additions/changes of categories...or maybe the ToC needs one extra layer of granularity to identify the themes that things are grouped by?

For example

* Generate image files from video
* Generate an animated GIF
* Create a video from imag(es) and audio

could become

* Work with Image Files and GIFs
  * Create a video from imag(es) and audio
  * Generate an animated GIF
  * Generate image files from video

Anyway, just thoughts! Don't wanna spark a death spiral of cataloguing issues!

**Comment by retokromer** [comment]
Thank you for clarifying, @privatezero!

**Comment by kfrn** [comment]
I wouldn't alphabetise for the reason @retokromer says. Not sure about creating meta-groupings in the ToC as @privatezero mentions - I see the benefits, but I think it could be a little unwieldy.  
Perhaps in reorganising the page, I've over-categorised? Should some of the sections merge back together? e.g. should _Generate image files from a video_ & _Create an animated GIF_ become simply _Create thumbnails or GIFs_?  
The ordering of the page could probably be improved a little bit.

**Comment by privatezero** [comment]
I tend to favor over-categorization myself, but unfortunately I think my instincts are always to push it to the edge of TOO much categorization which might be cumbersome (subcategories and cross-references!!) so please take all my opinions with a grain of salt ;-P

**Comment by retokromer** [comment]
We have to take account of our audience. (_Cum grano salis_ – more is too salty ;-)))

**Comment by ablwr** [comment]
See #262 

https://www.youtube.com/watch?v=6nr8hPnZfMU

**Comment by ablwr** [comment]
![under_construction](https://user-images.githubusercontent.com/3260492/31553437-7defda20-b008-11e7-9de1-cf010b5d028a.gif)

preparing another big change, hang tight

**Comment by kfrn** [comment]
You're on fire at the moment Ashley!

![](http://i.imgur.com/UFNeWe5.gif)

**Comment by retokromer** [comment]
Can this be closed?

**Comment by ablwr** [comment]
YES.
