### ISSUE TITLE
Refine the organisation of the page

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/ffmprovisr#237]
I got the ball rolling with #236, but I think more refinement can be done re: grouping commands into specific categories.

- Are current commands included under the right heading?
- Could commands currently listed under **Other** be moved elsewhere, perhaps under a new category?
   - example: do the commands relating to audio belong under a new heading?
- Are the current headings usefully named?
   - example: could **Change video properties**, which groups commands changing primary video properties like aspect ratio and colourspace, be better named?
- Could some things be better categorised?

etc etc.

@kieranjol expressed some interest in finding homes for some of the currently Misc items.    

If we have any lurkers who have been interested in contributing, this could be a good task for you to look at. 😁

**Comment by kfrn** [comment]
Some comments on this topic came up in #235.

What do you think of the following?

1. Is it worth merging back _**Generate image files from a video**_ & _**Create an animated GIF**_ to a single section, e.g. **Create thumbnails or GIFs**?

2a. What about creating a section called **Work with audio**, into which is collected the following:
- _Fix AV Sync: Resample audio_
- _Extract audio_
- _Combine audio tracks_ 
- _Create access MP3_

2b. and if so, should the current contents of **Normalize/equalize audio** become part of this section, or stay separate?
- _Flip phase shift_
- _Calculate Loudness Levels_
- _RIAA Equalization_
- _One Pass Loudness Normalization_
- _Two Pass Loudness Normalization_

**Comment by ablwr** [comment]
I agree with rolling images and gifs into one -- Create image-based derivatives? Although I prefer the more simple language you offer: "Create thumbnails or GIFs".

Considering the current size/scope of audio-based recipes, I think it's good to lump 'em all together. What do others think?

**Comment by privatezero** [comment]
This all sounds like a good idea to me, with the possible issue that if all the audio was lumped together it might confuse someone who was looking for the WAV -> mp3 and WAV ->AAC scripts that are contained in the Change Codec section.  

Also, in hindsight, looking at _Create access MP3_, that probably should be renamed something more explicit like _Append copyright notice to access mp3__ to differentiate it from the standard WAV -> mp3.

I would be happy to make that change once I get a moment!

**Comment by retokromer** [comment]
I second the idea to group the video codec recipes and the audio codec recipes in two distinct sections.

**Comment by ablwr** [comment]
Oh yeah, create access mp3 used to be longer and say "+ copyright something something" but I trimmed it to stop the website from being broken on mobile devices due to long button names. I'm thinking if we ditch the tooltips and change the buttons into not-buttons and let them wrap, just like the ToC, then we can go back to more descriptive names (like if the tooltip is longer, I'll replace the tooltip with the current shortened title).

**Comment by kfrn** [comment]
I think this is pretty well resolved for now, so I'll close this issue! Thanks for your help, everyone!
