### ISSUE TITLE
FFmpeg install instructions via linuxbrew

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#245]
Not an issue directly with ffmprovisr, but wanted to ping @retokromer that the instructions for installing linuxbrew provided in this link appear to be using old paths. Looks like linuxbrew has moved stuff around a little bit!

https://github.com/amiaopensource/ffmprovisr/blob/b483acdb6d97eb9faf7d1651a54d1c54bbac41f5/index.html#L55

I was setting up a new linux box and found success with:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`

to download linuxbrew and:

`echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.bashrc`

`echo 'export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"' >> ~/.bashrc`

`echo 'export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"' >> ~/.bashrc`
to add to path.

**Comment by retokromer** [comment]
Thank you very much, @privatezero! Should now be updated.
