### ISSUE TITLE
add CC-BY icon locally

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#249]
By using a local copy of the icon it works 100% also off-line. Otherwise the 0.01% will be a missing icon symbol on the page. (Nothing fundamental, just a graphical detail.)

**Comment by retokromer** [comment]
@ablwr I guess you can add it at almost no cost to your current PR.

**Comment by ablwr** [comment]
made a new one!

**Comment by retokromer** [comment]
Ah, OK… then I could have made it also myself, sorry for letting you do it.

**Comment by ablwr** [comment]
no prob, I already had it open
