### ISSUE TITLE
Worth adding how to decode a file with -f null - ?

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#25]
Is it worth showing how to just decode a file in order to check fixity against internal crcs in an mkv? I'm not sure if this is too obvious/simple?I'd like to get feedback on this before I create an entry.
Something like `ffmpeg -i input_file -f null -`

I would find this useful within a preservation context. I didn't know how to harness fixity info within a container/codec until @dericed showed me on twitter. Perhaps there's other benefits to this beyond fixity?

If it is worthy of inclusion, should it be called "verify embedded checksums" or should it just be called something general like "decode a file"? 
There's also the `err_detect` `bitstream` and `crccheck` tools but I don't see any benefit to these over just decoding to -f null - , though I'm probably using them incorrectly.

**Comment by dericed** [comment]
IIRC FFmpeg doesn't check fixity of mkv internal crcs. It will do so with ffv1 crcs though.

**Comment by kieranjol** [comment]
Ah, thanks for clarifying. Is it worth adding this info to ffmprovisr or is
ffv1 fixity too niche?

**Comment by ablwr** [comment]
I don't think ffv1 fixity is too niche. I'm also in favor of any contributions even if they seem niche or small. :pager:

**Comment by kieranjol** [comment]
Brillo! Will get this done over Christmas. Thanks guys.

**Comment by retokromer** [comment]
+1

**Comment by kieranjol** [comment]
added https://github.com/amiaopensource/ffmprovisr/commit/78f70f28f6162a75c96152a795abd84b784f821f
