### ISSUE TITLE
most popular recipes?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#251]
Hey,
this is a random thought, but I've been wondering about the possibility of seeing a list of most referenced recipes. Of course, I have no idea whether that would be possible, or how it could be implemented, but I'm generally curious to hear if others share my desire.
thanks!

**Comment by ablwr** [comment]
How would we know which recipes are the most referenced? We don't do any user tracking...

**Comment by retokromer** [comment]
Also in the part of the world where I am currently teaching, it’s often easier to use the off-line version, because WiFi might be a matter of chance.

**Comment by bturkus** [comment]
alright, cool. thanks for responding. closing now...
