### ISSUE TITLE
open call for new recipes!

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#254]
I know this might not be the best place for this, but Kelly Haydon and I will be teaching a video preservation class this semester, and we were interested in having the students contribute to some open source tools (avaa, ffmprovisr, qctools docs).

If anyone has any relatively easy recipes that they've been wanting to add (but haven't had a chance), please let me know.

@kieranjol would you mind de-self assigning #238?

**Comment by ablwr** [comment]
I THINK THIS IS GREAT

**Comment by ablwr** [comment]
I can't be biased since I work on all of these projects, but AVAA is probably the easiest both in editing and in finding things to add. It needs more examples but also could add more information for many artifacts, especially related to if the artifacts are fixable or not.

**Comment by bturkus** [comment]
here's the list I've been putting together for new AVAA entries (I have ex for all):

1” Type C Color Frame Error
F1 (PCM audio on videotape)
DPS-295 Artifact
EIAJ ‘Old Color’
Timecode and Line 21 CC

But some of these are pretty weak, so I'm all ears. Looking for like 5 AVAA, 5 ffmprovisr

**Comment by kfrn** [comment]
That's super cool @bturkus !  
I've also contributed to AVAA, I agree that one is probably easier to contribute to right now. A lot of pages need examples, more extensive descriptions, etc.  
With ffmprovisr, I think a lot of the basic recipes are already there, but I'll see if I could think of any. Maybe they could add an entry or two about ffmpeg concepts?

**Comment by ablwr** [comment]
Wow something ffmprovisr does need, though, is testers for all the recipes, to help us catch mistakes and maybe add improvements to them.

**Comment by kfrn** [comment]
Very good point. I think a big contribution could also be made by elaborating on recipes that aren't very fleshed out/well-explained.

**Comment by bturkus** [comment]
closing...couldn't make it happen this semester, but def in the future!
