### ISSUE TITLE
Tooltips?

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#257]
Do you find the hover-over tooltips useful? It seems like *most* of the time, we just repeat what we say on the button. I think the function that the tooltip serves most of all is that it is aesthetically pleasing to have something nice happen when hovering.

I bring this up also because on mobile, you have to tap twice to actually open the recipe now, because the tooltip gets in the way and appears on the first hover. If we restructure the website similar to the Table of Contents and button-text is allowed to become bigger, should we eliminate tooltips?

Or do people really love them? This is just my opinion.

**Comment by ablwr** [comment]
This is also part of my not-so-secret goal of freeing ffmprovisr from relying on the bootstrap-css/bootstrap-js/jQuery frameworks.

**Comment by kfrn** [comment]
I don't think they're useful. Kill 'em off I say.

**Comment by todrobbins** [comment]
I think tooltips could be useful for expanding initialisms (e.g. OCR, RIAA, SMPTE), but aside from that I'm with you in ditching Bootstrap cruft.

We could implement CSS-only tooltips: https://kazzkiq.github.io/balloon.css/

**Comment by ablwr** [comment]
I MURDERED
