### ISSUE TITLE
add note about codec defaults to video filtergraph commands

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#267]
not sure I understand exactly how ffmpeg works in all cases, but when a video filtergraph is called, and a codec isn't specified, it defaults to avc, right?

I've also been tripped up in the past by trying to copy codecs while filtering in some way. If you all agree, and it's not in there already, I think it could be a good idea for us to add some canned language about defaults and the need to re-specify if a user wants to stick with the codec of the original.

**Comment by privatezero** [comment]
I believe that FFmpeg has different defaults that kick in depending on what the file extension is for the output file (which will often result in avc).

**Comment by ablwr** [comment]
I've been burned here too, a lot, because I always forget. I think it is important to mention and thanks for bringing it up!

This could also be added to the Filtergraphs portion of the Advanced FFmpeg concepts section, or a new section specifically called Codec Defaults.

**Comment by privatezero** [comment]
A Codec Default section could be handy, because then we could note not only what codec things will default to, but what codec settings will be defaulted to (as that is definitely an easy thing to overlook!)

**Comment by ablwr** [comment]
Should I assign this to @bturkus ... or @bturkus's students? 😈

**Comment by bturkus** [comment]
heeheehee. maybe it'll be a team effort? 

can I self-assign, or do I not have the privileges?

**Comment by ablwr** [comment]
You should have privileges... but Reto's got ya

**Comment by kfrn** [comment]
Yeah, as @privatezero says, it depends on what you specify as the output wrapper, for example, MP4 defaults to H.264 & AAC.   
And indeed, the default encoding settings are important to note! The [transcode to H.264 recipe](https://amiaopensource.github.io/ffmprovisr/#transcode_h264) does include a note about what the default encoding settings are for H.264, but this type of information could be more widely explained.

I like the idea of adding a _Codec Defaults_ entry, perhaps in the **FFmpeg Basics** section?  
Not that it is basic _per se_, but IMO, a large part of using ffmpeg effectively is knowing your codecs and wrappers, and that's one of the things most likely to trip up a beginner.   
Then that entry could be linked to by the relevant recipes.  
Or a **Codec Defaults** section could work too, with individual entries.

**Comment by retokromer** [comment]
I suggest:
- to keep the descriptions in the recipes (e.g. the note about MP4/H.264 requiring AAC), because it’s directly related to the use of the recipe itself;
- to add a **Codec Defaults** either as an independent section or – possibly better – as one item of **Advanced FFmpeg concepts,** because I guess otherwise it would confuse the beginners.

**Comment by privatezero** [comment]
Added a section for this in https://github.com/amiaopensource/ffmprovisr/pull/338 - I'll leave this open as a reminder if people would like to expand on it with additional format defaults!

**Comment by ablwr** [comment]
New semester, @bturkus ! :eyes:

**Comment by privatezero** [comment]
as this has been built out a bit more, gonna close this with the caveat that more additions are always welcome!
