### ISSUE TITLE
Sizing problem in Firefox

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/ffmprovisr#270]
I usually use Chrome, but opened FF the other day and found something off with the sizing:

This is full-screen in Firefox (`56.0.1 (64-bit)`). Note the X-scroll:
![firefox_fullscreen](https://user-images.githubusercontent.com/16832997/31927939-ad47e54a-b8f2-11e7-8596-662230fe8a79.PNG)
As the spacing indicates, even when scrolled all the way right, there's not room for the side spacer.

I had a fiddle with the media queries, thinking it might be something to do with [this](https://github.com/amiaopensource/ffmprovisr/blob/fe937d7e4a8f9482ee2a5e44b6392c722183a43e/css/css.css#L60).  
Toggling off `max-width: 70%;` improved things a little, but didn't fix the problem. It looks like this is happening at the `body` level, anyway.

With `max-width: 70%;` turned off:
![firefox_fullscreen_mq](https://user-images.githubusercontent.com/16832997/31927941-ad7b5182-b8f2-11e7-9005-06fdacc700aa.PNG)

For comparison, here's how it looks in Chrome (`62.0.3202.62`):
![chrome_fullscreen](https://user-images.githubusercontent.com/16832997/31927938-ad142732-b8f2-11e7-9d87-9b38ace9f222.PNG)

@ablwr, can you offer your CSS expertise?

**Comment by ablwr** [comment]
Whoops, meant to look at this and didn't realize it was separate from your recent CSS fix. I just noticed this also! Hmm, it was fine before, I wonder what triggered it to act up again. I will look now.

**Comment by ablwr** [comment]
Oh oh, the problem I had before involved firefox's lack of support for word-break, so some of the recipes don't know how to shorten themselves so they continue kinda forever.

Applying break-all causes this kind of ugly behavior:

<img width="904" alt="screen shot 2017-10-31 at 21 51 32" src="https://user-images.githubusercontent.com/3260492/32256476-a616d69e-be85-11e7-94ad-9cfc7e3fc916.png">

making content hard to read. I'll try to get a solution in place though.
