### ISSUE TITLE
Avoid hyphenation of the command

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#276]
Is there a simple way in the CSS to avoid «hyphenation» of the command in the middle of a word, like `cop` and `y` as in the following example?

<img width="863" alt="bildschirmfoto 2017-11-01 um 16 47 39" src="https://user-images.githubusercontent.com/3246607/32283442-9bf07e14-bf24-11e7-9706-389f8645a300.png">

cc @ablwr @kfrn

**Comment by ablwr** [comment]
I can keep investigating the issue but that was what I just put into place to keep the code example from going over the page wide and messing up view in Firefox!

**Comment by retokromer** [comment]
FYI: I was using Safari here.

**Comment by ablwr** [comment]
Right, the line breaks happen in all browsers. The lack of linebreak overflow was previously causing the problems in Firefox.

**Comment by retokromer** [comment]
@ablwr Would adding`hyphens: none;` resolve this?
```
code {
  padding: 2px 4px;
  color: #c7254e;
  background-color: #f9f2f4;
  border-radius: 4px;
  word-break: break-all;
  word-wrap: break-word;
  white-space: normal;
  display: inline-block;
  hyphens: none;
}
```

**Comment by todrobbins** [comment]
`line-break: strict;` in the CSS should fix most cases of this, although Firefox is yet to implement... See: https://developer.mozilla.org/en-US/docs/Web/CSS/line-break

**Comment by retokromer** [comment]
Thank you, @todrobbins! I suggest that we move forward that way, and ignore Firefox.

**Comment by ablwr** [comment]
Firefox should not be left behind!

**Comment by retokromer** [comment]
I am unhappy with the idea of having to manage different CSS behaviours, because of the inconsistency of the current browsers.

**Comment by ablwr** [comment]
It breaks on `copy` because it is necessary, otherwise lines do not know how to break with something lengthy like `"[0:a:0]asplit=2[a][b];[b]afifo[bb];[1:a:0][bb]concat=n=2:v=0:a=1[concatout]"`.

**Comment by ablwr** [comment]
An example of why this linebreak has to happen is not for `copy` but for `loudnorm=dual_mono=true:measured_I=input_i:measured_TP=input_tp:measured_LRA=input_lra:measured_thresh=input_thresh:offset=target_offset:linear=true` within https://amiaopensource.github.io/ffmprovisr/#loudnorm_two_pass

**Comment by ablwr** [comment]
Ah! I have a compromise. One moment.

**Comment by ablwr** [comment]
#281 should resolve, re-open if insufficient
