### ISSUE TITLE
New recipe for embedding subtitles

### ISSUE THREAD

**Issue by federicomenaquintero** [amiaopensource/ffmprovisr#289]
I've been using this to embed a subtitle file into a movie file:

`ffmpeg -i input.mp4 -i subtitles.srt -c copy -c:s mov_text output.mp4`

I think this would be useful to have around.

**Comment by kfrn** [comment]
Ooh good one, I've used similar commands lots to mux in subtitles.  
Do you want to add the recipe yourself, or prefer one of us to do it?

**Comment by federicomenaquintero** [comment]
If you do it yourselves, great!  I really don't know the conventions you use here :)

**Comment by ablwr** [comment]
Ahhhh!!! Thanks. I will add. Double-thanks!

**Comment by federicomenaquintero** [comment]
O_O that was fast, thank you.  And now I know what options to use to keep things inside an mkv instead of repacking into an mp4 :)
