### ISSUE TITLE
Concat and transcode with the same script?

### ISSUE THREAD

**Issue by GregH18** [amiaopensource/ffmprovisr#292]
Hi all,
Wanted to say, I'm loving the newly organized ffmprovisr page. It makes finding the commands I like to use so much easier! 

I'm familiar with the join/concatenate script which works great, but I'm interning with @bturkus he thinks there is a way to combine the transcode script with the concatenate script. I've looked at the ffmpeg site:
https://trac.ffmpeg.org/wiki/Concatenate, but frankly, that really confuses me. 

We're trying to transcode 3 files, two of which are MPEG video with AC-3 audio and the third is MPEG video with PCM, but the audio for the third (PCM) is not there after transcoding. Ben was using this script `ffmpeg -f concat -safe 0 -i mylist.txt -c:v libx264 -c:a aac test2.mp4`

It would be cool if there were a script to concat and transcode at the same time. Any help would be appreciated!

Thanks!

**Comment by privatezero** [comment]
Pretty sure that if you are using inputs with different codecs you need to use the concat filter. Thanks for pointing out that this would be a good recipe to add!

For the time being, [this recipe](https://amiaopensource.github.io/ffmprovisr/#append_mp3) for appending an mp3 file to a wav file uses the concat filter and has a little explanation, so maybe it could help as an example for what you are trying to do?

**Comment by privatezero** [comment]
Maybe the examples in the [concat](https://ffmpeg.org/ffmpeg-filters.html#concat) filter doc are close enough to what you are trying to do to be helpful?

**Comment by kfrn** [comment]
Hi @GregH18, you might want to have a look at the PR I have just opened, #296, which includes a recipe for concat + transcoding. I'd really appreciate any feedback you have!

I think the recipe you are looking for is something like this (disclaimer: did not test with the exact same kind of files that you have):
```
ffmpeg \
-i mpegac3file1 \ 
-i mpegac3file2 \
-i mpegpcmfile \
-filter_complex \
"[0:v:0][0:a:0][1:v:0][1:a:0][2:v:0][2:a:0]concat=n=3:v=1:a=1[videoOut][audioOut]" \
-map "[videoOut]" -c:v libx264 \
-map "[audioOut]" -c:a aac \
output_file.mp4
```

**Comment by kfrn** [comment]
PR #296 adds a concat + transcode recipe, and I've also opened issue #298 about enhancing that command. Therefore, I'll close this issue.
