### ISSUE TITLE
New Recipe: Rewrap back to dv

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#295]
This is a bit of a note to self to add in this rewrap command helpfully supplied by @dericed for taking a DV stream that has been wrapped in something like mov and going back to a straight up .dv file

`fmpeg -i  dv.mkv -f rawvideo -c:v copy backto.dv`

Good to know that just doing a straight up `c:v copy` without the `rawvideo` tag seems to mess up some of the metadata!

**Comment by ablwr** [comment]
ping @privatezero ya still wanna add this? this is really useful.

**Comment by privatezero** [comment]
knew I was forgetting something! I'll get on it.

**Comment by privatezero** [comment]
Added in https://github.com/amiaopensource/ffmprovisr/pull/316
