### ISSUE TITLE
ImageMagick recipes

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#311]
As discussed in #310 and #309, we'd like to add an ImageMagick section to ffmprovisr, but we need recipes! Please share small scripts here!

**Comment by kfrn** [comment]
Very basic, but these are ones I have used:

Resize specifying new width:
`convert input -resize 750 output_750w.jpg`
(this script will also convert the format, if the output has a different file extension than the input)

Create grid of images:  
`montage @list.txt -tile 6x12 -geometry +0+0 output_grid.jpg` . 
(`list.txt` is a list of filenames)

**Comment by JonnyTech** [comment]
I use the mogrify command for resizing:

`mogrify -path ./resized/ -resize x1280 *.jpg`

Specify either width, height or both - new files end up in the resized folder.

You can even use a percentage of the size in place of the number of pixels.

**Comment by JonnyTech** [comment]
Create thumbnails of images:

`mogrify -resize 80x80 -format jpg -quality 75 -path thumbs *.jpg`

Using convert command, but don't think it likes wildcards:

`convert input.jpg -resize 80x80 -quality 75 thumbs/output.jpg`

**Comment by JonnyTech** [comment]
Remove (strip) exif data, place new files in stripped folder:

`mogrify -path ./stripped/ -strip *.jpg`

**Comment by nkrabben** [comment]
Post any image surgery, it's nice to run compare, analogous to framemd5

```
compare -metric ae original.jpg new.jpg null:
```
Lots of different metrics available
https://www.imagemagick.org/script/command-line-options.php#metric
I use ae (I think that's default) but sometimes pae and psnr. For most metrics, we're looking for an output of 0.

It also creates an image of the differences between the two you're comparing, but I throw that away (null:)

**Comment by kieranjol** [comment]
I actually tried this using Graphicsmagick but it should work the same in IM:
 `convert -verbose input_file`
Gives you a lot of nice metadata, but what's cool is the `signature`, which is kind of like a framesha256 for the image data, ignoring the metadata.

i was using grep to isolate the value:
 ```
convert -verbose input_file |grep -i
 signature
  Signature: 3fb67059dca860c483b1deac912973b76d48fa9f0114d63e8116cff69d55bb4c
```

It was handy to verify an ffmpeg DPX patch (noone's replied to me yet and I'm expecting Carl Eugen to say this is all a terrible idea) https://patchwork.ffmpeg.org/patch/7598/

**Comment by ablwr** [comment]
Added all the ones discussed above unless they were similar, so I am gonna close this issue. But more recipes are very welcome and can be added in the traditional ways (making an issue or a PR). Thanks everybody who contributed!
