### ISSUE TITLE
Suggested addition: Excerpt from end

### ISSUE THREAD

**Issue by mulvya** [amiaopensource/ffmprovisr#32]
Adapted from existing Excerpt to end

**Excerpt from end**

`ffmpeg -i input_file -sseof -5 -c copy output_file`

This command copies a video file starting from a specified time before the end of the file, removing everything before from the output. This can be used to create an excerpt, or extract content from the end of a video file.

**ffmpeg**
    starts the command
**-i input_file**
    path, name and extension of the input file
**-sseof -5**
    Tells ffmpeg what timecode in the file to look for to start copying, and specifies the number of seconds from the end of the video that ffmpeg should start copying. The end of the file has index 0 and the minus sign is needed to reference earlier portions. To be more specific, you can use timecode such as 00:00:05.
**-c copy**
    use stream copy mode to re-mux instead of re-encode
**output_file**
    path, name and extension of the output file

**Comment by retokromer** [comment]
Thank you very much!

**Comment by ablwr** [comment]
yayay thanks @mulvya! @retokromer ya gonna add this in? Today might be the day I organize these into categories.

**Comment by retokromer** [comment]
I’ll can do it «only» on Saturday.
@ablwr It’s fine with me if you re-organise the entries.

**Comment by ablwr** [comment]
@retokromer In that case, perhaps I will beat you to this. :D

**Comment by ablwr** [comment]
Resolves in https://github.com/amiaopensource/ffmprovisr/commit/e16fa215a7436b2b2161dcf6748c8eed39f163e1 but since I pushed straight to source please verify copy and close!

**Comment by mulvya** [comment]
Thanks for posting it. But the parameter guide underneath the command mentions `-ss 5` instead of `-sseof -5`

**Comment by retokromer** [comment]
@mulvya I've noticed it, and I'm trying to fix it. Yet on my computers the formula doesn't give the end, but the full clip. I'll check the documentation. Any hint?

**Comment by retokromer** [comment]
Perhaps the parameter `-sseof -5` must be before `-i input_file`?

**Comment by retokromer** [comment]
Yes, now should be OK. Please verify @mulvya and/or @ablwr.

**Comment by ablwr** [comment]
Clumsy me! Looks good now, thanks! This is why we PR. ;)
