### ISSUE TITLE
streaming access recipe

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#323]
Hey all,

I was thinking it might be beneficial to add some instructions for creating an mp4/aac specifically calibrated for streaming (with the fast start flag etc). It seems like this might be better as a separate recipe rather than as additions to the current mp4 transcode recipe, but I was wondering if people had thoughts about this? Also wanted to see what settings the rest of ffmprovisr land is using to see if there is consensus to inform a recipe!

**Comment by retokromer** [comment]
I’m completely in favour of streaming recipes! (I’m just incompetent to help…)

**Comment by kieranjol** [comment]
I think this would be really handy to add, I've never had a need for it
myself but I'm sure I will at some point.

**Comment by ablwr** [comment]
Hell yeah!

**Comment by ablwr** [comment]
@privatezero

**Comment by privatezero** [comment]
thanks for the ping - I'm still on it! Will whip something together in the not distant future

**Comment by ablwr** [comment]
@privatezero :neutral_face:

**Comment by privatezero** [comment]
HEY MAN

**Comment by privatezero** [comment]
Added a note (rather than separate recipe) to the current mp4 formula in https://github.com/amiaopensource/ffmprovisr/pull/339. Just contains the fast start flag - didn't get into specific bit rate settings etc.

**Comment by ablwr** [comment]
you da man
