### ISSUE TITLE
Show All Recipes button non-functional

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#324]
Just noticed that the `Show/hide all recipes` button is doing zilch on my end. Running Firefox 60.0.1 for Ubuntu 16.04.

**Comment by ablwr** [comment]
Uh oh! Firefox 60.0.1 on macOS is working fine for me. Are there any errors in the javascript console?

**Comment by privatezero** [comment]
I just tested at home on my laptop (Same version of FF as at work) and it is working fine for me here, so I am thinking it was just my janky work computer having some unrelated issue and faking me out. I did have my mouse/pointer control crash today (among other things) so yeah...there could be a bunch going on there! Closing as false alarm!!
