### ISSUE TITLE
H.264 lossy to lossless FFV1 transcoding increases file size by 3000%

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#327]
As reported on [twitter](https://twitter.com/k_grons/status/1011642837048463361). Thank you, @kgrons! Possibly either the existing recipe [Create FFV1](https://amiaopensource.github.io/ffmprovisr/#create_FFV1_mkv) needs to be amended or a new one is needed.

**Comment by retokromer** [comment]
An useful reference from [The archivist’s video codec and container FAQ](http://www.av-rd.com/knowhow/video/FAQ-digital_video_archiving.html#q_digital_source_file) by @pjotrek-b

**Comment by dericed** [comment]
As reported, it's not clear that an ffv1 output from an h264 input being 3000% larger is not the correct output. To change the recipe to force a `<3000% || >3000%` seems arbitrary. This would seem to require two passes, to first see the output = 3000% larger and then discard the output and somehow force an increase or decrease. Not sure this is worthwhile to just avoid an unlucky number. Thus far none of the twitter discussion or this thread has include any logs to verify the statistics, any steps to proceed would be guesswork.

**Comment by retokromer** [comment]
I suggest to indicate at least what is the mathematical minimum that can be achieved during the transcoding from lossy to lossless (with lossy content ;-) in some current archival situations. That way one knows if she/he is in a reasonable order or if «something» is going wrong. That‘s exactly what we are preparing for Memoriav and, as soon as ready, can be of course used here as well.

Alternatively we could explain how to calculate this, but the goal is not to frighten the user…

I neither can say if 3000% is reasonable or not in that case, because I don’t know the file. I can just say that with a test on one lossy real-world file on my workstation, I got a different result. No more, no less.

**Comment by ablwr** [comment]
I am still not understanding what is wrong with the script in question, which is provided as an example and is like, the most maxed-out preservation-heavy metadata-heavy version of a conversion, taking advantage of all of FFV1's features. No script is going to be suitable for every use case and all scripts on the internet should be reviewed carefully and critically, no matter how "vetted by professionals" they may be, for each unique need.

**Comment by retokromer** [comment]
At the moment, I would suggest to just amend the script with a caveat.

And, possibly, to add a table that puts intervals of values to Peter’s list. That way the user knows. Yet I personally don't have a clear idea about that for the moment.

**Comment by dericed** [comment]
I suggest that mathematical minimum is not a worthwhile goal in the context of preservation. Reducing slice count would lower data size but decrease resilience. Disabling slicecrc would lower data size but eliminate some strategies to conceal errors.

The idea that this issue is considered valid seems to only depend on secret information (the original user's unshared logs and @retokromer's unpublished memoriav work). I think the original script is fine. If you care to share publicly some information to indicate otherwise then please do, otherwise the references to secret data that we are not allowed to review simply seem to be trolling the project.

**Comment by retokromer** [comment]
Closing, because I don’t wish to be insulted here as well.

**Comment by pjotrek-b** [comment]
Sorry for necroposting, but @retokromer:
_Which "table with intervals of values" should be added to my list?_

(btw: I think I'll put "elaborate the 'lossy-to-lossless' topic on my FAQ page" on my todo-list :stuck_out_tongue_closed_eyes: )

**Comment by retokromer** [comment]
My first idea was just to add to the recipe a caveat saying that it’s not always a good idea to transcode. Because IRL one recipe’s user got in serious size trouble.

My second idea was to be more exhaustive: to include your list (or the link to) and add to this the intervals of size values per format one gets, when not following your advice. That way the cost of ignoring you would be known ;-)
