### ISSUE TITLE
CDDA Tools/Commands

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#340]
Thinking maybe we could use a section in the "Other Tools" for CLI tools/commands for ripping CDDA such ash:
* cdparanoia
* cdda2wav
* xld
* others?

Many of these tools are similar (such as using the paranoia library) but I thought maybe a quick blurb and command for each might be helpful!

**Comment by privatezero** [comment]
Possible sample command for cdda2wav:
`dda2wav -vall cddb=0 -t all -cuefile -paranoia paraopts=retries=200,readahead=600,minoverlap=sectors-per-request-1 -verbose-level all myfile.wav` or something along those lines. Thoughts? Suggestions for tools/commands?

I'll start trying to hammer something out later.

**Comment by kfrn** [comment]
I'm not familiar with these tools, so it sounds great to me!

**Comment by privatezero** [comment]
Here is a start anyway! https://github.com/amiaopensource/ffmprovisr/pull/345

**Comment by ablwr** [comment]
go go weaver!!

**Comment by bturkus** [comment]
hey. just wanted to say how awesome this new addition is. thanks @privatezero!! One small thought: would it be worth mentioning that your CD needs to be unmounted before running cdda2wav?

**Comment by privatezero** [comment]
@bturkus is that on macOS? Mount state didn't seem to make a difference for me on Linux, so that is good to know!

Reopening this to remind myself to test/add that note and cuz still want to add sections for other tools!

** Note to self to also add note about possible need for `install --devel` flag depending on drive

**Comment by privatezero** [comment]
Seems like a good place to close this for now!
