### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#342]
There is a missing `</div>` closing tag somewhere in `index.html`. Sorry, I do not have the time to delve into this now. However I will do it, if nobody does it during the next couple of weeks.

**Comment by privatezero** [comment]
Looks like I missed closing one at the very bottom of https://github.com/amiaopensource/ffmprovisr/pull/338? Right at https://github.com/amiaopensource/ffmprovisr/pull/338/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR2546. I'll make a PR!
