### ISSUE TITLE
Wish: reduce bloat

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#35]
Reduce the overall weight of the application with consideration to slow connections. This can be done by cutting out lazy dependencies on Bootstrap and jQuery and using only what is necessary.

**Comment by retokromer** [comment]
I agree, but, my opinion, it’s more important to realise #3 (Make accessible offline).

**Comment by ablwr** [comment]
Me too! I had kinda tacked this issue into that one which was the kind of scope creep that prevents the resolution of the first, main issue.

**Comment by retokromer** [comment]
Should we close this issue, @ablwr?

**Comment by ablwr** [comment]
Sure lets close this! I'm satisfied with the more important resolved issue of making sure this app works offline.
