### ISSUE TITLE
update to reto's homebrew installation instructions

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#355]
hey,
this might not be the best place for this, but @retokromer I noticed that the homebrew installation instructions on your website might need an update for 4.1+. Looks to me like sdl2 and (I believe) x265 now come standard. Am I right about this?
thanks,
ben

**Comment by retokromer** [comment]
Thank you, @bturkus! I'll check and update as soon as back home.

**Comment by kieranjol** [comment]
X265 does anyhow! Not sure about sdl2.

**Comment by retokromer** [comment]
@bturkus I checked and you are fully correct. I just updated (for Linuxbrew as well). Thanks again!
