### ISSUE TITLE
installation of FFmpeg using Brew

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#366]
Sadly, the Brew maintainers have decided to drop all options from their formulae. I’ll try to publish as soon as possible an alternate FFmpeg formula allowing again to install some additional options which are useful for the audio-visual archivists’ work:
- `--with-openjpeg` : Enables JPEG 2000 encoding and decoding.
- `--with-rubberband` : Enables the Rubberband audio filter, which allows time-stretching and pitch-shifting.
- `--with-tesseract` : Enables the Tesseract filter for optical character recognition, e.g. for extracting inter-titles or subtitles.

**Comment by privatezero** [comment]
Huh! That is unfortunate! Do you have a link to their discussion where they decided on that?

**Comment by retokromer** [comment]
Oh… there were many discussions at different formulae! I’m testing right now:
```
brew install avpres/formulae/ffmpeg
```
Possibly, you need to run:
```
brew uninstall --ignore-dependencies ffmpeg
```
before the new installation.

If it works fine, then we can move the formula to AMIA Open Source.

**Comment by retokromer** [comment]
I have updated the [installation instructions](https://avpres.net/FFmpeg/#ch1). It works fine on our end with the alternate formula.
