### ISSUE TITLE
Anchor expansion/location

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#368]
Currently internal links point to a location that ends up slightly below the actual linked location. Also, they don't seem to automatically expand. If there is a tweak to fix this we should probably look into it for enhanced usability!

**Comment by kfrn** [comment]
Good catch! The auto-expansion should be fixable - I won't have time to look at it in the coming week, but should be able to following that.

**Comment by ablwr** [comment]
I'm gonna add both of us to it, whoever gets a chance first!

**Comment by ablwr** [comment]
This seems to be working for me. Is this still an issue for you, @privatezero?

**Comment by todrobbins** [comment]
@ablwr same here. I just tested in Chrome, Firefox, and Safari on macOS.

**Comment by privatezero** [comment]
Yah, can confirm this is still an issue on my end in both Firefox and Chrome. This is just for internal links to other recipes such as those found in this recipe: https://amiaopensource.github.io/ffmprovisr/index.html#cd-emph-check. On my end at least, auto expand will work if the link is used 'fresh' but not once ffmprovisr is loaded.

**Comment by ablwr** [comment]
Oh, I see what you mean. That is not good!

**Comment by privatezero** [comment]
yeah - sorry my original wording was super vague!

**Comment by ablwr** [comment]
Have a fix in for this, but fixing another problem, and will send a PR shortly... I hope

**Comment by ablwr** [comment]
Resolved in https://github.com/amiaopensource/ffmprovisr/pull/385
