### ISSUE TITLE
Is there a file with all the commands ?

### ISSUE THREAD

**Issue by taschenbach** [amiaopensource/ffmprovisr#374]
I am looking for a file of just the commands and one line descriptions. I am about to upload a new FFmpeg command program and want to include the ffmprovisr FFmpeg commands. I can copy and paste from the html but having something parsable would be great so it can auto update with the new recipes in the future.

**Comment by retokromer** [comment]
Hello Tommy! This does not exist yet, but I am quite sure I can parse the code in order to generate it and add a file here. Would you prefer a plain ASCII file or a structured one (XML, JSON, etc.)?

**Comment by taschenbach** [comment]
The format I arbitrarily chose is a plain text file with the '#' character indicating title/comment on a line preceding the command.
Example:
#Change container (rewrap)
ffmpeg -i input_file.ext -c copy -map 0 output_file.ext

Here is what I have copied so far https://drive.google.com/open?id=1COHl9ft7G9BTZYw8evJy4WDUuugz0Gup

**Comment by retokromer** [comment]
I have written a short Perl script to extract it and will try to condense it into an one-liner.

**Comment by retokromer** [comment]
@taschenbach Does this output https://github.com/amiaopensource/ffmprovisr/pull/376/commits/5b795e53dde7783c01bd82f22a653d30c9b0f7c8 satisfy your request?

**Comment by retokromer** [comment]
@taschenbach Here is a one-liner which works on Linux and macOS:

```
curl https://amiaopensource.github.io/ffmprovisr/index.html -s | grep -E '<h3>.*</h3>|<p><code>.*</code></p>' | sed 's/.*<h3>\(.*\)<\/h3>/# \1/' | sed 's/.*<code>\(.*\)<\/code>/\1/' | grep -v '\*\*\*' | sed -e 's/<[^>]*>//g'
```

I have opened an issue to improve the use of the `<h3>`and `<p><code>` tags in order to get a proper output.

**Comment by ablwr** [comment]
Very cool @retokromer !!!

**Comment by taschenbach** [comment]
@retokromer thats great, thank you.
