### ISSUE TITLE
modify the use of the `<h3>` tag

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#377]
I guess, it’s not possible to satisfy https://github.com/amiaopensource/ffmprovisr/issues/374 with a one-liner, but tedious looping is needed, because the use of `<label class="recipe" for="...">` and `<h3>` are not univoque.

- A dirty hack could be to add a pseudo-class to the main `<h3>` of the recipes.
- In my opinion, a better solution would be to use the `<h3>` tag (or another heading tag) exclusively for the main title of the recipes.

In both cases the `index.html` file could then be parsed by something like:

```sh
cat index.html \
  | grep -E '<h3>.*</h3>|<p><code>.*</code></p>' \
  | sed 's/.*<h3>\(.*\)<\/h3>/# \1/' \
  | sed 's/.*<code>\(.*\)<\/code>/\1/' \
  | grep -v '\*\*\*' \
  | sed -e 's/<[^>]*>//g'
```

The command is composed by the following piped elements:

- read the `index.html` file content
- select the relevant lines (title and command)
- replace the spaces before the `<h3>` tag by the comment sign `# `
- remove the spaces before the `<code>` tag
- remove the sample example
- remove the tags inside the commands, such as `<em>`

**Comment by retokromer** [comment]
FYI: the updated one-liner which parses the `<h3>` and `<p><code>` tags in the online version of ffmprovisr is:

```sh
curl https://amiaopensource.github.io/ffmprovisr/ -s | grep -E '<h3>.*</h3>|<p><code>.*</code></p>' | sed 's/.*<code>\(.*\)<\/code>/\1/' | sed 's/.*<h3>\(.*\)<\/h3>/# \1/' | grep -v '\*\*\*' | sed -e 's/<[^>]*>//g'
```

**Comment by taschenbach** [comment]
@retokromer I was able to use your file and included most of the commands in my new GitHub project https://github.com/ColorlabMD/FFCommand_Engine

Thank you and all the ffmprovisr contributors

**Comment by retokromer** [comment]
@taschenbach Thank you for the feedback and for this additional FFmpeg tool. I will test it with students… next week!

**Comment by ablwr** [comment]
eyyyyy this is cool! Thanks @taschenbach

**Comment by kfrn** [comment]
Cool stuff!

**Comment by retokromer** [comment]
Ping! Is there any opinion from the maintainers about this?

>[…] the use of `<label class="recipe" for="...">` and `<h3>` are not univoque.
>- A dirty hack could be to add a pseudo-class to the main `<h3>` of the recipes.
>- In my opinion, a better solution would be to use the `<h3>` tag (or another heading tag) exclusively for the main title of the recipes.

(I would like to open a PR with the preferred solution.)

**Comment by ablwr** [comment]
I prefer the latter -- better structure!

**Comment by kfrn** [comment]
Same as @ablwr. Semantic HTML!

**Comment by retokromer** [comment]
Thank you! As said, this is also my preferred solution. I will open a PR as soon as possible.

**Comment by ablwr** [comment]
ping @retokromer

**Comment by retokromer** [comment]
Sorry, I didn’t had the possibility to make this so far. It’s necessary to modify some `<h3>` tags.

**Comment by retokromer** [comment]
To make the [one-liner](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/scripts/get_recipe_list) generating the output format needed for the [FFCommand_Engine](https://github.com/ColorlabMD/FFCommand_Engine), i.e.
```
# recipe title
recipe code
```
it’s needed to have an univoque usage of a tag, e.g. `<h3>`. If I have catched them all, the “offending“ lines are:

- https://github.com/amiaopensource/ffmprovisr/blob/ea2c29a38c326b1d433591337438f721a9a2e2f8/index.html#L75
- https://github.com/amiaopensource/ffmprovisr/blob/ea2c29a38c326b1d433591337438f721a9a2e2f8/index.html#L114
- https://github.com/amiaopensource/ffmprovisr/blob/ea2c29a38c326b1d433591337438f721a9a2e2f8/index.html#L164
- https://github.com/amiaopensource/ffmprovisr/blob/ea2c29a38c326b1d433591337438f721a9a2e2f8/index.html#L792

**Comment by ablwr** [comment]
ping @retokromer !

**Comment by retokromer** [comment]
@ablwr Could you add a new style for the “offending” lines (e.g. same look but different meaning)? Then the change is easy to do.

**Comment by ablwr** [comment]
thought you were gonna do it

**Comment by retokromer** [comment]
@ablwr I could just change `h3` to `h3, h5` and then the “offending” lines fo `h5`.
