### ISSUE TITLE
Transform SD into HD with pillarbox (with yadif??)

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#380]
Hi Everyone,

I was recently asked to make some 1080p MP4s from SD originals, and I found myself a little confused about where to incorporate deinterlacing into our standard SD-->HD with pillarbox command. After running some tests, it seemed to me that the best result came when using yadif sooner, rather than after scaling and padding. I guess I'm wondering 2 things: (1) could anyone confirm that yadif first is the best best, and (2) should we think about adjusting our script in some way to help people in this situation out?

Thanks,

Ben

**Comment by dericed** [comment]
If you are scaling interlaced content be sure that the scalar knows that. See the `interl` option at https://ffmpeg.org/ffmpeg-filters.html#Options-1.

**Comment by privatezero** [comment]
That's a good point! The script should probably be updated to be more clear about handling interlacing, as I can imagine that a significant amount of the use cases would in fact be targeting an interlaced source!

**Comment by kfrn** [comment]
I'd definitely deinterlace before scaling.  
It looks like you've been working from the [SD -> pillarboxed HD](https://amiaopensource.github.io/ffmprovisr/index.html#SD_HD_2) - the deinterlacing step is included in the [NTSC SD -> pillarboxed HD](https://amiaopensource.github.io/ffmprovisr/index.html#ntsc_to_h264) command (in the `Work with interlaced video` section)

The two commands are pretty similar other than the `yadif` step - the first one also converts the colourspace.

**Comment by kfrn** [comment]
Between the existing NTSC SD -> pillarboxed HD recipe, and the note added in #434, I think this is now resolved. I'll close the issue, but you're welcome to reopen it if we need more discussion. Cheers :)
