### ISSUE TITLE
Add 'Micropops' as sister project

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#381]
Ari's rad work at [MIPoPS Micro Services](https://pugetsoundandvision.github.io/micropops/) should be added to the list of 'sister projects' built on the ffmprovisr skeleton!

Ping! @alavigne12

**Comment by kfrn** [comment]
Good call! Feel free to go ahead and add it :)

**Comment by privatezero** [comment]
Looks like @alavigne12 is on it!

**Comment by privatezero** [comment]
added in https://github.com/amiaopensource/ffmprovisr/pull/382
