### ISSUE TITLE
Adding Bash Scripts to ffmprovisr

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#39]
Continued from here, if that's OK? https://github.com/amiaopensource/ffmprovisr/pull/36

Im not sure how ye see longer scripts within ffmprovisr.. Go with bash or also include other languages that also allows Window support? Or do ye want to keep the site to single ffmpeg commands?

It could be handy to knock up a simple watermark script, where the font size is calculated in proportion to video height? 
Or possibly check what the codec and wrapper is of each file in a directory, and transcode if certain conditions are met?

Here's a python one that (last time I checked) works in windows and OSX - haven't tried Ubuntu yet but it should work. 
https://github.com/kieranjol/pyh264bitc/blob/master/py_h264_bitc.py
I need to change a good few things in that script, mostly based on things I've learned from ffmprovisr! Also there's some things in there that are specific to where I work which should be removed.
The main difference in terms of OS adjustments is getting python to escape the colons in the timecode/fontpath in different ways depending on which OS it detects.

**Comment by ablwr** [comment]
I think longer scripts are useful, especially to people that aren't brand-new to using ffmpeg, but am wondering about, like what you said, equal support regardless of user operating system.

Since we moved forward with categories, we could have a category not based on type of use but based on extended use of ffmpeg within scripts.

**Comment by retokromer** [comment]
:+1: 

I was thinking at Nicole’s script. And I will think about the interoperability.

**Comment by kieranjol** [comment]
I think my workplace seems to be in the minority in terms if having windows as well as osx workstations.
Perhaps it could be OK to have multiple languages represented,as one could understand the general logic of how to harness FFmpeg in different contexts? I am familiar with bash and python,but would love to see a perl or ruby FFmpeg script as it would allow me to see familiar use cases within an unfamiliar language.
There could also be an option to choose a language for a task,though that would require volunteers to "port" the scripts.
P.S, I would gladly try to find the time to do some of that porting.

**Comment by retokromer** [comment]
I just tested: runs fine on Ubuntu 14.04 LTS and on Slackware 14.1.

**Comment by retokromer** [comment]
I am very familiar with Perl (< 6). A large part of my websites is generated on the fly by Perl and MariaDB! Yet Python or Ruby are more sexy. I do not have a clear idea about Perl 6, just made recently some tests: https://gist.github.com/retokromer/bdea769e90fdc277fc13

**Comment by retokromer** [comment]
No, sorry, on Ubuntu I got:

```
[17:25:48]why@why:~/Desktop$ '/home/why/Desktop/test.py' '/home/why/Desktop/test' 
480.0
640.0
Traceback (most recent call last):
  File "/home/why/Desktop/test.py", line 58, in <module>
    print  textoptions
NameError: name 'textoptions' is not defined
[17:26:00]why@why:~/Desktop$ 
```

**Comment by retokromer** [comment]
I guess if you set the `_platform` then it will work.

**Comment by kieranjol** [comment]
Yeah,I never set the Linux platform check now that I think of it! I'm
hoping the osx escaping will carry over to Linux though. Will work on that
next week.
Anyhow, I remember having difficulty tracking down examples of FFmpeg
python scripts at the time. Lots of bash out there. I'd love to see some
perl! Just a general suggestion anyhow.

Edit: just saw your perl now. I think that's fascinating! Also, I know now what you mean about Nicole's example. It's a bash script but still a nice one liner.

**Comment by retokromer** [comment]
I have tried to fix it. But now knowing Python, I didn't succeed. It was better and better, and finally a mess. Now I am going to prepare our dinner. Perhaps I try again after.

**Comment by kieranjol** [comment]
I'm back at a computer now. Will give it a go, but any other additions would be more than welcome!
Looks like the _platform value for Ubuntu 14.04 is `linux2` (looks like most linux distros, including Ubuntu are just `linux` - also it looks like it requires different escaping from OSX.

**Comment by kieranjol** [comment]
Fixed for PAL in here: https://github.com/kieranjol/pyh264bitc/commit/c15ce53d01e5ac9171b2aa4064da76327566e223
I just put an NTSC file through and dropframe semicolons aren't escaped, so they fail. I generally only think in PAL terms but I try to make everything work if possible. Also I should add a `or _platform = "linux"` as I'm not sure how common `linux2` is as a value. I must also get ready for dinner!

**Comment by retokromer** [comment]
More generally speaking, for adding Bash scripts info ffmprovisr, I guess we should include OS X and Linux users, as well as Windows users having installed `cygwin` or `msys` on their computers. Then, if I understand correctly, it should work. I'll try to find such a testing machine.

**Comment by retokromer** [comment]
Bash should be functional on Windows 10 installations soon. That would make things easy.

**Comment by ablwr** [comment]
Do we feel this is ... resolved?

**Comment by kieranjol** [comment]
I think so anyhow. It is possible to run the bash scripts on ffmprovisr in a cross-platform way, so this issue is no longer relevant. Feel free to reopen.
