### ISSUE TITLE
MKV -> mp4 rewrap command possibly misleading?

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#392]
I've just gotten some user feedback that the recipe at https://amiaopensource.github.io/ffmprovisr/index.html#mkv_to_mp4 is a little problematic from a user perspective in our expected use case of libraries/archives.

Having the `-c:v copy` flag in the command will cause this to fail in the event of someone trying to run it on an ffv1/mkv file. This _seems_ to me at least to be a problem as within the target audience of ffmprovisr, probably a lot of people will be trying to find commands to use on that flavor of file.

Could this possibly be deleted as it is a little redundant with the basic rewrap command and the access mp4 command? Or clarified/cross linked more fully?

**Comment by kieranjol** [comment]
I'm in favour of deletion. I was initally going to suggest switching to something more flexible like mov, but I think that the basic_rewrap recipe makes this pretty redundant, and I agree on the confusion. Thanks for relaying the user feedback!

**Comment by kfrn** [comment]
Yep, I think the functionality is covered by the [basic rewrap](https://amiaopensource.github.io/ffmprovisr/index.html#basic-rewrap) command - I vote to remove [MKV to MP4](https://amiaopensource.github.io/ffmprovisr/index.html#mkv_to_mp4).

Happy for one of you to go ahead, otherwise I can do this when I'm at home tonight

**Comment by privatezero** [comment]
Cool! I agree with ya both! Thanks @kfrn! I'd do it, but I'm wrapping up my current job this week so am swamped with transition prep!

**Comment by ablwr** [comment]
In full support!

**Comment by retokromer** [comment]
Nice catch!

**Comment by retokromer** [comment]
Is this issue still one?

**Comment by privatezero** [comment]
I think this can be closed as the related formula was deleted!
