### ISSUE TITLE
Integrate this head switching noise cover script

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#42]
FFmpeg dropped some knowledge into my timeline when I was complaining about the weather and I need to drop that knowledge into this! https://twitter.com/FFmpeg/status/695689188205731846

**Comment by retokromer** [comment]
What kind of filtering would be a good example for an archival context?
https://ffmpeg.org/ffmpeg-filters.html#drawbox

**Comment by ablwr** [comment]
I figured the example they gave was a good one, for covering up the head switching noise. I don't see much of a use for archival purposes but maybe cleaning up something for access?

**Comment by retokromer** [comment]
May this be closed?

**Comment by ablwr** [comment]
Yes!
