### ISSUE TITLE
wishlist: link directly to a recipe

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#43]
As the number of recipes increases, I think it could be useful to be able to link directly to a recipe. 
I don't know how to implement this, but if there's any repetitive retrospective data entry required to make those links, I'll volunteer to do it, once I know roughly what to do.

Thanks!

**Comment by ablwr** [comment]
This is a great idea!!!

**Comment by retokromer** [comment]
:+1:

**Comment by todrobbins** [comment]
Should be relatively simple to add [URI fragments](https://www.w3.org/DesignIssues/Fragment.html) via `id` values for each recipe.

**Comment by ablwr** [comment]
I still need to do this, oops! also ++@todrobbins

**Comment by kieranjol** [comment]
Not sure if this route would work, but if you did one or two, I'd try to
emulate your coding and do the rest. Haven't a clue how to do it from
scratch!

**Comment by todrobbins** [comment]
@ablwr BUMP

Do you want me to try?

**Comment by ablwr** [comment]
The new sister site, CRALS, just integrated this feature if you want to give it a shot! https://github.com/dd388/crals/blob/gh-pages/js/js.js

**Comment by ablwr** [comment]
@todrobbins of course I want you to try! Yayayay

**Comment by kieranjol** [comment]
https://github.com/amiaopensource/ffmprovisr/pull/64 Here's a stab at it anyhow!

**Comment by todrobbins** [comment]
Looks great! Closing the issue.

**Comment by retokromer** [comment]
Close this, because solved by https://github.com/amiaopensource/ffmprovisr/pull/64.
