### ISSUE TITLE
ffmprovisr broken on Windows Terminal

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#440]
The command [`ffmprovisr`](https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/scripts/ffmprovisr) doesn’t work on Windows Terminal, neither online nor offline.

**Comment by privatezero** [comment]
Thanks for reporting! I should be able to look at this later this week, once I get access to my windows machine. (Currently my only way of getting on Windows is via remote desktop from a Mac with a Japanese keyboard layout, which makes script work on the remote machine **incredibly** aggravating)

**Comment by retokromer** [comment]
Thank you, @privatezero! Possibly I will also also have the time give a try during the second half of the week. (I could provide a Thai keyboard… ;-)

**Comment by kfrn** [comment]
Cheers @privatezero! I don't have access to a Windows machine, so cannot offer to look at this :(

**Comment by privatezero** [comment]
Will have to do some more testing later, as my 'social distancing' window where I can be in office is ending, but an initial test on my end (Ubuntu 18.04 app in Windows 10) showed that `xdg-utils` is not installed by default. Since the `ffmprovisr` command relies on `xdg-open`, this might be a fail point.

**Comment by retokromer** [comment]
(On a side note: in my opinion, “physical” distancing is more appropriate than “social”.) 
I guess, tomorrow evening I can perform some tests; otherwise only on Friday.

**Comment by privatezero** [comment]
Just remoted in to that machine, and after installing `xdg-utils` within the Linux subsystem, the `ffmprovisr` command is working correctly for firing up the online documentation at least.

**Comment by retokromer** [comment]
@privatezero Also on Terminal or only on Subsystem?

**Comment by retokromer** [comment]
I just tested, also on Terminal, therefore I am closing this one. We could include a test for presence on Linux into the formula.
