### ISSUE TITLE
Add ffmpeg-artschool as sibling project?

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#447]
@bturkus et al, what do you think? I think there's enough similarity in the two projects, it'd be nice to have them connected in the family tree (I think ffmprovisr is already connected on the https://github.com/amiaopensource/ffmpeg-artschool resources page).

**Comment by kfrn** [comment]
I'm in favour! Great project, by the way, @bturkus et al 😍

**Comment by bturkus** [comment]
yeah! great idea, thanks!

**Comment by kfrn** [comment]
Added in https://github.com/amiaopensource/ffmprovisr/pull/448, thanks! 👍
