### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#451]
Heyooo, I saw GitHub just released this new feature, Discussions.

I set up one by default, here: https://github.com/amiaopensource/ffmprovisr/discussions/450

But what does everyone think? Should we turn it on, keep it off, keep using Issues, direct people elsewhere? It could be a way for more shy folks to ask questions that aren't exactly ffmprovisr "Issues", but general questions about FFmpeg. I haven't really looked into the purpose/potential of this new feature yet.

**Comment by kieranjol** [comment]
I say keep it up, thanks for adding it!

**Comment by privatezero** [comment]
Yah, might as well? Seems like "Issues" for things that aren't "Issues" so might have its uses!

**Comment by kfrn** [comment]
I'll be the voice of dissent 😅, I don't see much value in having both Issues and Discussions, especially because there hasn't been much going on here in the last while. But I don't really mind if we have this feature. 😄

**Comment by ablwr** [comment]
Yeah I don't know that it will add much -- the hurdle for engagement is the act of posting at all, not because the Issues tracker is not a Discussion tracker. At least, that's what I assume?

**Comment by kfrn** [comment]
> Yeah I don't know that it will add much -- the hurdle for engagement is the act of posting at all, not because the Issues tracker is not a Discussion tracker. At least, that's what I assume?

Yeah, that's pretty much my take 🤷‍♀️😄

**Comment by ablwr** [comment]
This was not used so I just closed it, and I'll close this comment too.
