### ISSUE TITLE
update link for qemu qed ?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/ffmprovisr#452]
hi everyone,

I'm not 100%, but it's looking like the QEMU QED is out of date; could someone confirm? 

Thanks!

Ben

**Comment by privatezero** [comment]
Good catch! Yes - on my end I am just getting re-routed to a Gitlab login page

**Comment by ablwr** [comment]
@eg-tech halp!

**Comment by retokromer** [comment]
Was it not integrated into the regular QEMU?

**Comment by EG-tech** [comment]
ah, sorry y'all, there was some re-org on the EaaSI GitLab and the repo got moved so it broke the GitLab Pages domain. still up but at:
https://eaasi.gitlab.io/program_docs/qemu-qed/

I can make a PR

**Comment by retokromer** [comment]
resolved in https://github.com/amiaopensource/ffmprovisr/pull/453 and https://github.com/amiaopensource/ffmprovisr/pull/454
