### ISSUE TITLE
Should we add somewhere Rec. 601 and Rec. 709?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#46]
I am thinking about SD to HD using
`colormatrix=bt601:bt709`
and  HD to SD using
`colormatrix=bt709:bt601`
@kieranjol @ablwr Any thoughts?

**Comment by kieranjol** [comment]
Definitely,I'd be interested,and I know it's the kind of thing that my
colleague in programming would be interested in using at some stage, so I'm sure it'd be beneficial to others.

**Comment by retokromer** [comment]
OK, I'll prepare a draft.

**Comment by ablwr** [comment]
+1

**Comment by retokromer** [comment]
I’m preparing the examples for BAVC we can «recycle» here.

**Comment by kieranjol** [comment]
Brilliant, thanks Reto!

**Comment by retokromer** [comment]
I'm hesitating if it's better to include it, as a special case, into:
- https://amiaopensource.github.io/ffmprovisr/#SD_HD
- https://amiaopensource.github.io/ffmprovisr/#HD_SD

or if it's better to write two special recipes, as I did for BAVC:
- https://avpres.net/FFmpeg/SD_HD.html
- https://avpres.net/FFmpeg/HD_SD.html

Any preferences?

**Comment by kieranjol** [comment]
Hi Reto,

Maybe it should go into both? It seems like ffmpeg won't enable rec709 by
default if rescaling rec601 to HD? I am not that knowledgeable about these
standards, but it seems like it's important information to be added to the
pre-existing recipes. I think the color matrix change is important enough
to also warrant its own recipe, as I could imagine someone looking
specifically for that information and it might elude them if it was only in
https://amiaopensource.github.io/ffmprovisr/#HD_SD

-K

**Comment by ablwr** [comment]
I'm not at all hip to these so I defer to you two princes (and others reading this)!

**Comment by retokromer** [comment]
Note to self: Correct meta-data by passing additional options.

**Comment by retokromer** [comment]
Hmm... Our current recipe is 4:3 to 16:9 and not SD to HD. I guess we should add a specific SD to HD one, which my include the colour space issue.

**Comment by ablwr** [comment]
+1 for these improvements

**Comment by retokromer** [comment]
OK, I'll do this.
