### ISSUE TITLE
Add dedicated section for -nostdin flag?

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/ffmprovisr#463]
Howdy all, I've seen people run into looping issues by not using the `-nostdin` flag enough times that it seems like we might want to stick it into ffmprovisr. Wasn't sure if the best approach was adding this to its own section (as I did in this [quick branch](https://github.com/amiaopensource/ffmprovisr/tree/nostdin) or adding it into some of the existing Preservation concepts sections.

My gut said to make it more obvious by having it as its own section - but even if that is the case wasn't sure about placing it in 'Advanced Concepts' like I did in that branch, or if it makes more sense somewhere else.

Thoughts?

**Comment by kieranjol** [comment]
I think it’s in the perfect place, and after seeing that option a million
times in scripts, I never knew what it actually did! Thanks for the
addition, thumbs up from me.

K

**Comment by retokromer** [comment]
In my opinion as well, it is the best place to add this piece of information.

**Comment by ablwr** [comment]
TY @privatezero !!!
