### ISSUE TITLE
Error when installing ffmpeg on Mac using avpres.net instructional

### ISSUE THREAD

**Issue by eliseschierbeek** [amiaopensource/ffmprovisr#466]
I'm attempting to install FFmpeg on Mac OS Big Sur 11.7.1 using the avpres.net instructions for Mac (linked from FFmprovisor). I am using the following commands:

```
brew tap avpres/formulae
brew install --with-openjpeg --with-rubberband --with-svt-av1 --with-tesseract avpres/formulae/ffmpeg
```
I'm receiving back:

```
==> Installing avpres/formulae/ffmpeg --with-openjpeg --with-rubberband --with-svt-av1 --with-tesser
==> Installing FFmpeg with options...
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/5.1.2_2 --enable-shared --cc=clang --host-cflags= --host-ldf
Last 15 lines from /Users/lbosch/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-opencl
--enable-audiotoolbox
--enable-videotoolbox
--enable-libopenjpeg
--enable-librubberband
--enable-libsvtav1
--enable-libtesseract

ERROR: libmp3lame >= 3.98.3 not found
```

The install worked on my home computer, but not my office machine. I was able to install the avpres formulae FFmpeg using `brew install ffmpeg`.

**Comment by retokromer** [comment]
Thank you for reporting! The issue should be filed at the [formula’s repository](https://github.com/AVpres/homebrew-formulae/issues) rather than here.

Two questions:
- On which system did you get the error message?
- What is the output of `lame --version`?

**Comment by eliseschierbeek** [comment]
Thanks for your response! 

The error showed up on Mac OS Big Sur 11.7.1 (work computer). To clarify, I was able to install FFmpeg using `brew install ffmpeg` on that same work computer. 

The output of `lame --version` is `-bash: lame: command not found`

**Comment by retokromer** [comment]
Then I guess `brew install lame` before using the formula should resolve the issue.

It’s strange: usually the FFmpeg compilation tests that. But I will check if the formula should be amended, in order to avoid this error message. Thanks again for reporting.

**Comment by retokromer** [comment]
@eliseschierbeek Could the issue be solved?

**Comment by retokromer** [comment]
ping @eliseschierbeek

**Comment by eliseschierbeek** [comment]
`brew install lame` solved the issue
