### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#47]
Someone just asked if they could use this template for another project and I realized we don't have a license! I'm happy with the most open CC license. Can I get a +1?

**Comment by retokromer** [comment]
For software I prefer the MIT license, yet I am fine with CC licence (all my websites are CC BY). :+1:

**Comment by ablwr** [comment]
Yeah... this is definitely more on the "website" category than "software" category. Thankyew!
