### ISSUE TITLE
extract audio 

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#49]
Saw someone asking about this on the internet so a mental reminder to add script that extracts audio without loss from a video file: `ffmpeg -i video.[mp4] -vn -acodec copy audio-only-file.[aac]`

**Comment by kieranjol** [comment]
:+1:

**Comment by retokromer** [comment]
The command `ffmpeg -i input_file -c:a copy -vn output_file` should work with any input and any audio codec.

**Comment by ablwr** [comment]
👍 👍 @retokromer !

**Comment by retokromer** [comment]
@ablwr You may copy & paste this: http://avpres.net/FFmpeg/av_sound.html (or I can do it).

**Comment by retokromer** [comment]
Please check @ablwr and/or @kieranjol. Thank you! (Sorry, I pushed instead of making a pull request.)

**Comment by kieranjol** [comment]
Nice! :+1:  
P.S Checked, and all is well.

**Comment by ablwr** [comment]
LGTM 👍

**Comment by retokromer** [comment]
Thank you!
