### ISSUE TITLE
Wish - png watermark overlay

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/ffmprovisr#71]
I'm currently working on scripts that automate the addition of head and tail plates to a .mov, while adding a transparent png watermark that kicks in after 3.5 seconds.
`ffmpeg -safe 0 -f concat -i mylist.txt -i "/Users/bla/playertests/logo.png" -c:v prores -filter_complex "overlay=:enable='between(t,3.5,2000)':main_w-overlay_w-5:5,yadif" outputrigh12345.mov`
I'll add something like this over the coming days.

**Comment by ablwr** [comment]
Great!!!

**Comment by kfrn** [comment]
Folks, just wanted to say that I'm loving all the ffmprovisr action lately. Can't wait to check it out more fully when I'm back from holiday :)

**Comment by kieranjol** [comment]
Looking forward to having you back, enjoy the holidays!

**Comment by dericed** [comment]
When will this be done?

**Comment by ablwr** [comment]
IN THE COMING DAYS @kieranjol ?!?!?!

**Comment by kieranjol** [comment]
Sure! I've been meaning to go through old issues and clean up my unfinished
work.

**Comment by ablwr** [comment]
No rush on anything B-) I was just doing the same!

**Comment by kieranjol** [comment]
@kfrn  has inspired me to get this done finally. Apologies for delay.

**Comment by retokromer** [comment]
Done by https://github.com/amiaopensource/ffmprovisr/pull/104

**Comment by kieranjol** [comment]
Ha! You beat me to it. Thanks!
