### ISSUE TITLE
Interlaced ProRes

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#72]
At a some point, I guess, we should also consider an example of interlaced ProRes.

**Comment by kieranjol** [comment]
Good idea, especially considering the benefits of Kostya's encoder in
regards to interlacement
https://github.com/mediamicroservices/mm/commit/c022a1104e8f3b384273fbde1de8be2293a5c405

**Comment by retokromer** [comment]
If I remember correctly, the `-c:v prores_ks` is only good for interlaced, but for progressive it's slower as `-c:v prores`. Therefore we should use `prores` "as default" and `prores_ks` only for interlaced. I also guess that ProRes produced today should be progressive, but for legacy we need indeed to deal with interlaced. Please correct me if I am wrong.

**Comment by retokromer** [comment]
Thank you, @kieranjol, this is what https://github.com/mediamicroservices/mm/commit/c022a1104e8f3b384273fbde1de8be2293a5c405 (and the link there) says. Yet I will do some benchmark, as I am still feeling we should change only for interlaced, and not as a general rule for ProRes, because of the performance.

**Comment by retokromer** [comment]
Hmm... at the 1st benchmark the `prores_ks` says:

```
[prores_ks @ 0x690180] Packet too small: is 237874, needs 275122 (slice: 3396). Correct allocation is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[prores_ks @ 0x690180] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
```

**Comment by kieranjol** [comment]
Hi Reto, I totally agree on only using `prores_ks` for interlaced items. I must admit, for access purposes, I've used the regular prores encoder and I haven't found any issues for TFF files, or clients haven't mentioned any either. I haven't done much rescaling though.

**Comment by retokromer** [comment]
Does anyone know how (un)stable `prores_ks` is today? Both my interlaced and my 4:4:4 files seem not to be (completely) correct… 👎

**Comment by kieranjol** [comment]
That is worrying. @dericed is using it at work I think, so perhaps he can chime in? What's the issue with the files?

**Comment by retokromer** [comment]
I will test with 4K resonance patterns (or parts of it).

**Comment by retokromer** [comment]
Hmm… I am even more and more confused by the different results I got using `prores` and `prores_ks`, as well as using Final Cut 7, Final Cut X and Resolve 12.5.

**Comment by retokromer** [comment]
I suggest to add notes in the recipe at https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/index.html#L71 regarding:
- interlacement
- propes_ks
- ProRes 4444

**Comment by dericed** [comment]
With prores_ks you can reduce the discrepancies in Apple environments by setting the vendor tag falsely (though...). I filed a related ticket here. http://trac.ffmpeg.org/ticket/6025

**Comment by retokromer** [comment]
Yes, I have seen this.

(Not a topic for ffmprovisr: I would like an implementation with the file close to propes_ks (there are also issues, but in my opinion definitively less important) and with the speed of prores!)
