### ISSUE TITLE
Lossless Segmentation and Concatenate for Preservation

### ISSUE THREAD

**Issue by audiovisualopen** [amiaopensource/ffmprovisr#76]
Hi all, as archives may wish to create preservation clips in a lossless fashion from digital masters, maybe instructions on lossless segmentation and and concatenation would be beneficial?

As there is already in commands for clipping and concatenate (Join files together/Trim a video) without re-encoding, maybe they could be added to the preservation section as well with an emphases on the stream copy function:
 -c copy
use stream copy mode to re-mux instead of re-encode

thanks and what a great resource.

regards,
Andrew

**Comment by retokromer** [comment]
Hello Andrew,

as lossless, do you mean something like the following?
- https://avpres.net/FFmpeg/sq_YUV422_10.html
- https://avpres.net/FFmpeg/sq_YUV422_8.html

Best regards, Reto

**Comment by audiovisualopen** [comment]
Hi Reto,

I think your instructions to transcode an image sequence is very valuable and should also be included.

In terms of using lossless processing, I was more thinking about the great feature in FFMPEG to create files without re-encoding, highlighting the lossless nature, speed and low compute requirements of -c copy. As an example, this might be needed when a full broadcast compile news videotape is digitised, and individual news items can then be made as a unique preservation file.

regards,
Andrew

**Comment by retokromer** [comment]
Thank you, Andrew, for clarifying this to me. Best regards, Reto

**Comment by retokromer** [comment]
CC @kieranjol 
In terminal:
`split -b1m input_file part_`
`cat part_* > output_file`
would make it (in my example 1M parts).

**Comment by kieranjol** [comment]
Hi! I'll try to give this a go over the weekend.

**Comment by retokromer** [comment]
I guess this is not an FFmpeg-related issue, but are e.g.
`split -b1m input_file part_`
and
`cat part_* > output_file`
working under Windows? And, if so, should I add this to ffmprovisr?

**Comment by kieranjol** [comment]
Hi Reto, similar story to the framemd5 thread. Those tools are not available in the standard windows terminals but work very well in git bash.
I split and reconstructed an ffv1.mkv with matching checksums.
I'm not sure of the benefits of adding this to ffmprovisr as the split parts didn't play back. They did work fine if I transcoded to mpeg2 though. Perhaps the `cat` part could be helpful for certain file types, but i think `-f concat -c copy` is preferable?

**Comment by retokromer** [comment]
I guess `copy \b input_file_1 + input_file_2 + input_file_3 output_file` works in DOS (`\b` for binary mode).

Yet I think this does not fit into ffmprovisr. Thoughts?

**Comment by ablwr** [comment]
Are your reasons for thinking it doesn't fit just based on it not being an ffmpeg command? I'm in favor of the idea of expanding the scope to include non-ffmpeg commands if they are related to the same end goal of supportive scripting a/v preservation. But if the reason is lack of use case, I defer.

**Comment by kieranjol** [comment]
Just to flag that there are ffmprovisr forks that may be more suited, such
as the sourcecaster: https://datapraxis.github.io/sourcecaster/ and CRALS:
http://dd388.github.io/crals/

**Comment by retokromer** [comment]
We can include non-FFmpeg commands, but in this case e.g. the difference between drag&drop, `cp`, `ditto`, `rsync` etc. would be more important for audio-visual [digital] archivists, in my opinion.

**Comment by retokromer** [comment]
More thoughts?

**Comment by pjotrek-b** [comment]
Wanted to mention that using split/cat only works for raw or streamable data.

Saw that "Join files together" is already using FFmpeg's concat filter.
If this issue is still open due to the open question of how to deal with non-FFmpeg commands, wouldn't it be clearer to open a new issue for that topic?

Smartypants Peter :stuck_out_tongue_winking_eye:

**Comment by retokromer** [comment]
As @pjotrek-b suggested, closing this one in favour of https://github.com/amiaopensource/ffmprovisr/issues/168.
