### ISSUE TITLE
-report parameter

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#86]
We should find something nice that is improved by the use of the `-report` parameter. Suggestions welcome!

**Comment by kieranjol** [comment]
I'm thinking that adding `-report` to the [batch processing recipe](https://amiaopensource.github.io/ffmprovisr/#batch_processing) would be very useful. Perhaps to the [checkffv1 fixity recipe](https://amiaopensource.github.io/ffmprovisr/#check_FFV1_fixity) as well?

**Comment by retokromer** [comment]
The batch recipe needs completion, in my opinion. (E.g. change in order to work from everywhere, i.e. not requesting to be in the same directory as the files.)

**Comment by retokromer** [comment]
@kieranjol Good idea! I think, we could start with the [checkffv1 fixity recipe](https://amiaopensource.github.io/ffmprovisr/#check_FFV1_fixity) which don't need more re-factoring. Do you have the time?

**Comment by kieranjol** [comment]
Yes,Reto. I will try to get to it soon.

**Comment by retokromer** [comment]
Thank you, @kieranjol! I close this issue.
