### ISSUE TITLE
Transcoding NTSC <-> PAL

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#9]
Will be provided "tomorrow".

**Comment by ablwr** [comment]
I agree that "tomorrow" is never "only a day away."

**Comment by ablwr** [comment]
I bet @kieranjol has these handy

**Comment by kieranjol** [comment]
I honestly don't. We have a handful of ntsc tapes and none have been ingested. Sorry Ashley.

**Comment by retokromer** [comment]
I’ll add this as soon as I’ll find the time to do so. I couldn’t find a student to do it…

**Comment by ablwr** [comment]
@kieranjol and @retokromer you are both the best!

**Comment by retokromer** [comment]
Where can I easily find short real world NTSC examples to test the commands?

**Comment by kieranjol** [comment]
I have often used an example from Internet archive, pretty sure it's
uploaded by dave

https://archive.org/details/test20100622_v210_and_ffv1

**Comment by dericed** [comment]
it was. I should prolly update it to v3.

**Comment by retokromer** [comment]
Is it planned to update this? For the moment I’ve tested only on fake (aka self generated) NTSC.

**Comment by retokromer** [comment]
@dericed Are you planning to update the NTSC examples?

**Comment by retokromer** [comment]
I am closing this old issue. When I will have access to real world files (not self generated ones), I will add this recipe.
