### ISSUE TITLE
Script to convert DVD (.iso) to (something else)

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/ffmprovisr#91]
@kfrn has agreed to do this. Making an issue so we know it's a work in progress.

**Comment by retokromer** [comment]
Convert to Matroska with all the DVD features, as explained by Steve Lhomme?

**Comment by kfrn** [comment]
I'll dig into this over the next 2 or 3 weeks!
@retokromer, I'm not aware about this, do you have a link?

**Comment by retokromer** [comment]
No, not yet. I am just thinking about Steve Lhomme’s presentation in Berlin on why and how he designed Matroska that way.

**Comment by retokromer** [comment]
@kfrn: I cannot delve deeper into that now, but this may be inspiring: https://github.com/Matroska-Org/dvdmenuxtractor

**Comment by kfrn** [comment]
I didn't forget about this, but my computer is broken at the moment! When it's fixed I'll get onto it

**Comment by retokromer** [comment]
No rush!

**Comment by ablwr** [comment]
Pinging @kfrn !

**Comment by kfrn** [comment]
Hey, thanks for the reminder. :) Sorry folks, life has been crazy in the last while. If it's okay, I'll try to have a good look at this over the next fortnight, and if I don't come up with something decent, it's up for grabs.

**Comment by retokromer** [comment]
Done with https://github.com/amiaopensource/ffmprovisr/pull/103
