### ISSUE TITLE
ffmpeg -h foo=bar

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/ffmprovisr#93]
@kieranjol Maybe you could add here as recipe the information you posted on FFmpeg-user? The general command with the examples `ffmpeg -h encoder=ffv1` and `ffmpeg -h muxer=matroska` would be very useful, in my opinion. (If you don’t have the time, just let me know, and I’ll do.)

**Comment by kieranjol** [comment]
Great idea, Reto. I'd like to give it a go and will let you know within a
few days if I can't get to it. It's interesting that the topic has appeared
on twitter and ffmpeg-user in the space of a few days :)

**Comment by ablwr** [comment]
And CELLAR too, thanks to @retokromer ;D

👍
