### ISSUE TITLE
Script to convert still images to GIF?

### ISSUE THREAD

**Issue by kgrons** [amiaopensource/ffmprovisr#98]
Use Case: with exported thumbnails from video, want to make 'preview' GIF that's still low-res enough to be used as a thumbnail supplement.

Possible starting point: [Create animated gif from a set of jpeg images stackoverflow question](http://stackoverflow.com/a/29542944)

**Comment by ablwr** [comment]
Totally kinda thought we already had this in the beast. Can do, will do, thank you.

**Comment by ablwr** [comment]
Resolves in #102
